### ISSUE TITLE
Strange behavior in mf.analyze()

### ISSUE THREAD

**Issue by alarese** [pyscf/pyscf#2152] opened 2024-04-02 18:24 UTC
I am observing strange results with the Mulliken populations and Mulliken charges using the `mf.analyze()` function following:
```
mf = scf.ROKS(mol)
mf.max_cycle = 500
mf.conv_tol = 1.e-9
mf.xc = 'BP86'
mf.chkfile = chkfile.chk
mf = scf.newton(mf)
mf.kernel()
mf.analyze()
```
However, this behavior is not observed when loading the checkpoint file separately and calling the `mf.analyze()` function:
```
mol = scf.chkfile.load_mol('chkfile.chk')
mf = scf.ROKS(mol)
mf.__dict__.update(scf.chkfile.load('chkfile.chk', 'scf'))
mf.analyze()
```

Is there an issue in the DFT calculation or is this an issue solely with the `mf.analyze()` function?

**Comment by fishjojo** [comment] 2024-04-08 03:30
Hi @alarese, can you please provide a runnable example? Thanks.

**Comment by alarese** [comment] 2024-04-12 18:15
Here is an example for an oxidized high-spin Fe-S cluster
```
from pyscf import gto, scf, dft

mol = gto.Mole()
mol.atom = """
  Fe  5.20408995351399      1.16403089906140     -7.86817581839586
  S   3.86423526622517     -0.49421398515857     -8.72824796983818
  S   5.26051750606299      1.31768074320476     -5.52910079821434
  S   4.44652924740886      3.28239962602700     -8.53203841092078
  S   7.23649634493687      0.49368844519430     -8.71384400393211
  Fe  5.89632462846407     -1.16355138757718     -9.57556310141167
  S   5.83826756343465     -1.31463078389089    -11.91483074196588
  S   6.65463772577934     -3.28280014508219     -8.91535140905808
  C   5.63722027703029      4.38328594611438     -7.67256498594917
  H   6.62778711698636      4.32550328851670     -8.14795085631675
  H   5.28138346361616      5.42586665702203     -7.72311267397208
  H   5.74096012768995      4.07860342251436     -6.61992312045450
  C   3.52520349901006      1.79473275348390     -5.16978247834543
  H   2.84600560697674      0.95429142136781     -5.37564639953852
  H   3.42997692905282      2.07641145298515     -4.10785883618591
  H   3.22664052161476      2.64290345091368     -5.80459208674982
  C   5.46204216348024     -4.38231730405316     -9.77395725912807
  H   5.81717277774582     -5.42521372078074     -9.72490825106935
  H   4.47218465293951     -4.32442056062284     -9.29713553874003
  H   5.35736711302135     -4.07633192533243    -10.82611016542062
  C   7.57312619224089     -1.79165498471851    -12.27660120337246
  H   7.66678197328732     -2.07276842769741    -13.33880706606651
  H   8.25260756041927     -0.95131496849907    -12.07127060232346
  H   7.87244178906239     -2.64017991299249    -11.64262622263014
"""
mol.basis = 'def2-TZVP'
mol.verbose = 4
mol.spin = 10
mol.charge = -2
mol.build()

mf =scf.ROKS(mol)
mf.max_cycle = 500
mf.conv_tol = 1.e-8
mf.xc = 'BP86'
mf.chkfile ='test.chk'
mf = scf.newton(mf)
mf.kernel()
mf.analyze()

```
with this input, the mf.analyze() gives spin populations such as 
```
pop of  0 Fe 4dxy      27948543.09525
```
and Mulliken charges such as 
```
charge of    0Fe =   -27948631.10604
charge of    1S =   -78542298.49565
```
However, these values are not replicated when I load the checkpoint file in a separate python script and call mf.analyze()

**Comment by sunqm** [comment] 2024-08-12 01:37
I cannot reproduce this error. It can be issues that has been fixed in the new release. If you still get this error in new version, please consider to provide a docker image to help us identify the problem.

**Closed by sunqm** 2024-08-12 01:37 UTC
