### ISSUE TITLE
Variation between qcint and libcint integral libraries results on diamond 

### ISSUE THREAD

**Issue by tamigoldzak** [pyscf/pyscf#1969] opened 2023-11-22 08:32 UTC
_Description_
In PySCF version 2.4, I am encountering issues during MP2 correlation calculations with periodic boundary conditions (PBC) on diamond, using the 'ccpvdz' basis set and k-points set to 1,1,1. There are notable variations in results between the qcint and libcint libraries, both version 6.0.0.

While the qcint library leads to an unconverged SCF energy, the libcint library successfully converges.
Additionally, when executing `test_kpoint.py` from `pyscf/pyscf/pbc/mp/test`, both libraries fail the `test_h4_fcc_k2_frozen_df_nocc_high_cost` with similar AssertionErrors.
However, an additional failure occurs with the qcint library in `test_kmp2_with_cderi`, indicating a more significant discrepancy from expected values.

_Steps to Reproduce_
1. Run the PySCF calculation script (`mp2_sos.py`, attached to this issue) using PySCF version 2.4 with the qcint library (version 6.0.0).
2. Note the output and error messages (attached as `qcint.out` & `qcint.err`).
3. Repeat the process using the libcint library (version 6.0.0).
4. Compare the output and error messages (attached as `libcint.out` & `libcint.err`).
5. Run `test_kpoint.py` with both libraries and note the test results.

Expected Behavior
The SCF energy should converge consistently in MP2 calculations with PBC on diamond, using the 'ccpvdz' basis set and k-points 1,1,1, irrespective of the library used. Additionally, the standard test script `test_kpoint.py` should exhibit similar behavior across both libraries.

Actual Behavior
Discrepancies between the libraries are evident:
[pyscf_issue.zip](https://github.com/pyscf/pyscf/files/13435595/pyscf_issue.zip)

- **With qcint Library**: Unconverged SCF energy and additional failure in `test_kpoint.py` (specifically in `test_kmp2_with_cderi`).
- **With libcint Library**: Converged SCF energy but shares a common failure in `test_kpoint.py` (in `test_h4_fcc_k2_frozen_df_nocc_high_cost`).

Environment
- **Operating System**: Rocky Linux 9.2
- **Python Version**: 3.9.16
- **Hardware**: 
  - Lenovo ThinkSystem SR630 V2
  - 2x Xeon 6338 processors
  - 1TB RAM (64 x 16 GB)
  - 1.92 TB NVMe storage

Attached Files
- Input File: `mp2_sos_py.txt`
- Output and Error Files: 
  - `qcint_out.txt`
  - `qcint_err.txt`
  - `libcint_out.txt`
  - `libcint_err.txt`
- Test Output and Error Files:
  - `test_kpoint_libcint_out.txt`
  - `test_kpoint_libcint_err.txt`
  -  `test_kpoint_qcint_out.txt`
  - `test_kpoint_qcint_err.txt`
  
[test_kpoint_qcint_out.txt](https://github.com/pyscf/pyscf/files/13435625/test_kpoint_qcint_out.txt)
[test_kpoint_qcint_err.txt](https://github.com/pyscf/pyscf/files/13435626/test_kpoint_qcint_err.txt)
[test_kpoint_libcint_out.txt](https://github.com/pyscf/pyscf/files/13435627/test_kpoint_libcint_out.txt)
[test_kpoint_libcint_err.txt](https://github.com/pyscf/pyscf/files/13435628/test_kpoint_libcint_err.txt)
[qcint_out.txt](https://github.com/pyscf/pyscf/files/13435629/qcint_out.txt)
[qcint_err.txt](https://github.com/pyscf/pyscf/files/13435630/qcint_err.txt)
[mp2_sos_py.txt](https://github.com/pyscf/pyscf/files/13435660/mp2_sos_py.txt)

**Comment by sunqm** [comment] 2024-01-01 17:59
I'll close this issue as the problem cannot be reproduced. Feel free to reopen the issue.

**Closed by sunqm** 2024-01-01 17:59 UTC

**Comment by sunqm** [comment] 2024-01-25 08:52
qcint v6.0 introduces a bug in the int2e_sph integral function for certain general contracted basis. The bug is fixed in v6.1.1 . The issue in your case is unlikely caused by this bug. But this could be a related issue.

**Comment by sunqm** [comment] 2024-02-03 18:58
@tamigoldzak  qcint bug has been identified and fixed in v6.1.2. The error should be fixed in PySCF-2.5 release.
