### ISSUE TITLE
TypeError in the multi-root dmrgci

### ISSUE THREAD

**Issue by jamcas** [pyscf/pyscf#405] opened 2019-08-09 13:58 UTC
Hello, I followed the example/mrpt/41-for_state_average.py to do a nevpt2 calculation for an excited state, but, unfortunately, something went wrong:
```
from pyscf import gto, scf, mcscf, dmrgscf

mol = gto.M(
    atom = [
        ['O', ( 0., 0.    , 0.   )],
        ['H', ( 0., -0.757, 0.587)],
        ['H', ( 0., 0.757 , 0.587)],],
    basis = '6-31g',
    symmetry = 1)

mf = scf.RHF(mol)
mf.kernel()

mc = dmrgscf.DMRGSCF(mf,4,4)
mc.state_average_([0.5,0.5])
mc.run()

mo = mc.mo_coeff

mc = mcscf.CASCI(mf,4,4)
mc.fcisolver = dmrgscf.DMRGCI(mol)
mc.fcisolver.nroots = 2
mc.run(mo)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/lib/misc.py", line 472, in run
    self.kernel(*args)
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/mcscf/casci_symm.py", line 63, in kernel
    return casci.CASCI.kernel(self, mo_coeff, ci0, verbose)
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/mcscf/casci.py", line 818, in kernel
    cas_natorb=self.natorb, verbose=log)
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/mcscf/casci.py", line 877, in canonicalize_
    sort, cas_natorb, casdm1, verbose, with_meta_lowdin)
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/mcscf/casci.py", line 396, in canonicalize
    casdm1 = mc.fcisolver.make_rdm1(ci, mc.ncas, mc.nelecas)
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/dmrgscf/dmrgci.py", line 318, in make_rdm1
    return DMRGCI.make_rdm12(self, state, norb, nelec, link_index, **kwargs)[0]
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/dmrgscf/dmrgci.py", line 332, in make_rdm12
    file2pdm = "spatial_twopdm.%d.%d.txt" %(state, state)
TypeError: %d format: a number is required, not range
```
I also tested in CASCI and found that it works well.

And if i don't set mc.fcisolver.nroots =2,the calculation can continue. Is the result obtained at this time credible?
```
from pyscf import gto, scf, mcscf, dmrgscf, mrpt

mol = gto.M(
    atom = [
        ['O', ( 0., 0.    , 0.   )],
        ['H', ( 0., -0.757, 0.587)],
        ['H', ( 0., 0.757 , 0.587)],],
    basis = '6-31g',
    symmetry = 1)

mf = scf.RHF(mol)
mf.kernel()

mc = dmrgscf.DMRGSCF(mf,4,4)
mc.state_average_([0.5,0.5])
mc.run()

mo = mc.mo_coeff

mc = mcscf.CASCI(mf,4,4)
mc.fcisolver = dmrgscf.DMRGCI(mol)
mc.run(mo)

mps_nevpt = mrpt.NEVPT(mc,root=1).compress_approx().kernel()
```

**Comment by sunqm** [comment] 2019-08-13 07:21
I cannot reproduce this error.  Can you check the version at
```
/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/__init__.py
```

The second script for NEVPT2 is all right. It's the recommended way to run state-average DMRG-CASSCF then NEVPT2

**Comment by jamcas** [comment] 2019-08-13 07:49
My version is 1.6.1. I am going to upgrade and test it to see if it still produces errors.

**Comment by jamcas** [comment] 2019-08-13 09:25
After I upgrade to the latest version 1.6.3, the error is still there.

**Comment by jamcas** [comment] 2019-08-16 06:49
I found this error is raised by isinstance function of  the following codes:
https://github.com/pyscf/pyscf/blob/3ed5a44ec0cd1bef70bb68576968e09c2614ab37/pyscf/mcscf/casci.py#L83
https://github.com/pyscf/pyscf/blob/3ed5a44ec0cd1bef70bb68576968e09c2614ab37/pyscf/mcscf/casci.py#L401

After I change```
        if (isinstance(ci, (list, tuple)) and
            not isinstance(mc.fcisolver, addons.StateAverageFCISolver)):
```
to         
```
        if (isinstance(ci, (list, tuple, **range**)) and
            not isinstance(mc.fcisolver, addons.StateAverageFCISolver)):
```, this error is fixed:
```
from pyscf import gto, scf, mcscf, dmrgscf

mol = gto.M(
    atom = [
        ['O', ( 0., 0.    , 0.   )],
        ['H', ( 0., -0.757, 0.587)],
        ['H', ( 0., 0.757 , 0.587)],],
    basis = '6-31g',
    symmetry = 1)

mf = scf.RHF(mol)
mf.kernel()

mc = dmrgscf.DMRGSCF(mf,4,4)
mc.state_average_([0.5,0.5])
mc.run()

mo = mc.mo_coeff

mc = mcscf.CASCI(mf,4,4)
mc.fcisolver = dmrgscf.DMRGCI(mol)
mc.fcisolver.nroots = 2
mc.run(mo)

WARN: Mulitple states found in CASCI solver. First state is used to compute the natural orbitals in active space.

CASCI state 0  E = -75.9774363937779  E(CI) = -6.07459456016701  S^2 = 0.0000000
CASCI state 1  E = -75.5779925101576  E(CI) = -5.67515067654676  S^2 = 0.0000000
<pyscf.mcscf.casci_symm.SymAdaptedCASCI object at 0x2b4167a0e160>
```

**Comment by sunqm** [comment] 2019-08-16 13:41
Thanks for digging into the problem. This bug is fixed in the latest updates.

**Comment by jamcas** [comment] 2019-08-17 02:15
It's very happy for me to contribute to pyscf.

**Closed** 2019-10-07 06:43 UTC
