### ISSUE TITLE
Unexpected multicollinear DFT energy in PySCF-2.3.0

### ISSUE THREAD

**Issue by Shunsum** [pyscf/pyscf#1878] opened 2023-09-25 06:50 UTC
Hi, I am trying to calculate the energy of certain atoms using the "mcol" functional in PySCF. However, the results I got from this approach differ significantly from those obtained from the "col" and "ncol" methods, while the pyMC module gives the reasonable outputs. There appear to be some bugs in the calculation of $E_\text{xc}^\text{MC}$ in the latest PySCF. Below are some details about my test.
# Results from PySCF
```python
from pyscf import gto, scf
mol = gto.M()
mol.atom = '5' # just take boron as an example
mol.spin = 1
mol.basis = 'cc-pvdz'
mol.verbose = 5
mol.build()

mf = scf.GKS(mol)
mf.kernel()
# converged SCF energy = -24.3492647963336  <S^2> = 0.75127893  2S+1 = 2.0012785

mf.collinear = 'ncol'
mf.kernel()
# converged SCF energy = -24.3492647959041  <S^2> = 0.75127893  2S+1 = 2.0012785

mf.collinear = 'mcol'
mf.kernel()
# converged SCF energy = -124.197902208194  <S^2> = 0.75127893  2S+1 = 2.0012785
```
# Results from pyMC
```python
# --snip--
from pyMC import gksmc
mf = gksmc.GKSMC(mol)
mf.kernel()
# converged SCF energy = -24.3492647961974  <S^2> = 0.75127893  2S+1 = 2.0012785
```

**Comment by sunqm** [comment] 2023-10-09 00:38
It is caused by a bug in the previous release of mcfun. It is fixed with MCfun v0.2.2 release. See also https://github.com/Multi-collinear/MCfun/issues/4

**Closed by sunqm** 2023-10-09 00:38 UTC
