### ISSUE TITLE
CASSCF energy convergence instability

### ISSUE THREAD

**Issue by iliamazin** [pyscf/pyscf#912] opened 2021-04-19 14:31 UTC
Hi all,

I am writing to report an issue I have observed w/ seemingly non-deterministic behavior of the CASSCF energy convergence.

My test system is an HF molecule w/ (4e,4o) active space and 6-31g* basis set.

When doing this I have observed that there are two distinct energies that appear as the converged value:
-100.051474622473
-100.014572844223

The lower energy value requires 40+ iterations to converge while the higher energy result is usually obtained within 20 macro iterations or so.

To check whether or not this is unique to the version of PySCF I am using, I ran the same CASSCF calculation several times w/ the same starting orbitals using PySCF versions 1.62 and 1.7.6a1. 5 out of the 11 calculations w/ PySCF version 1.76a1 and 4 out of 11 calculations w/ PySCF version 1.62 resulted in the higher '-100.014573' energy value.

I have attached relevant input/output files for this issue.

Best,
Ilia Mazin

[hf_4e4o.txt](https://github.com/pyscf/pyscf/files/6336745/hf_4e4o.txt)
[hf_4e4o_pyscf162.txt](https://github.com/pyscf/pyscf/files/6336747/hf_4e4o_pyscf162.txt)
[hf_4e4o_pyscf176a1.txt](https://github.com/pyscf/pyscf/files/6336756/hf_4e4o_pyscf176a1.txt)

**Comment by jamesETsmith** [comment] 2021-04-22 13:23
@iliamazin, a couple of ideas:

1. Have you tried turning symmetry on? I would try turning the verbosity up (>=5) and having a look at the orbital overlap with the previous and initial orbitals at each CASSCF iteration. My guess is that bc symmetry is not turned on you have degenerate orbitals that are rotating in/out of the active space. Highly symmetric species like this can be a real pain some times.
2. Have you tried `mc2step()` instead of `mc2step()`? `mc1step()` is an approximate method and may be contributing to the instability you're seeing.
3. I would also try a different set of initial orbitals, maybe NOs from MP2 and see if the problem persists

**Comment by sunqm** [comment] 2021-04-26 00:07
4 orbitals and 4 electrons in active space is not a typical choice of the system. It corresponds to an active space that correlate 4 electrons in HOMO-1 HOMO, LUMO, LUMO+1 which are two pi occupied orbitals and two unoccupied sigma orbitals. You would easily converge to a symmetry broken solution or other problematic solution. It's better to put enough pi orbitals or enough sigma orbitals to be correlated. There are a couple of plugins that can help you to choose a proper acitve space. For example
```
from pyscf.mcscf import dmet_cas
# correlate sigma orbitals
ncas, nelecas, mo = dmet_cas.guess_cas(mf, mf.make_rdm1(), mol.search_ao_label(['H 1s', 'F 2s', 'F 3s', 'F 2pz', 'F 3pz']))
mc = pyscf.mcscf.CASSCF(mf, ncas, nelecas).run(mo)

# correlate multiple pi orbitals
ncas, nelecas, mo = dmet_cas.guess_cas(mf, mf.make_rdm1(), mol.search_ao_label(['F 2px', 'F 2py', 'F 3px', 'F 3py']))
mc = pyscf.mcscf.CASSCF(mf, ncas, nelecas).run(mo)
```

**Comment by ssh2** [comment] 2021-04-26 12:38
Thanks for the comments, @jamesETsmith and @sunqm . I agree with all of what you said in terms of solving the problem. @iliamazin ran some tests and will report the results. 

I do have one question though: Is it normal for a CASSCF code to show such a nondeterministic behavior? I've used the CASSCF code in ORCA and MOLPRO quite extensively and I don't think I remember problems like this, but it might be only me. Has any one else experienced similar problems with other codes? 

The reason why I am asking is because we have seen these nondeterministic results for other systems with more reasonable active spaces and sometimes this turns out to be a real problem for some benchmarks and applications. Most frequently the problem arises when we have symmetry turned off or for systems with low symmetry (like C1). Shouldn't the results of the code be more reproducible?

**Comment by sunqm** [comment] 2021-04-26 21:20
I observed nondeterministic results before. The optimization path may be slightly different in different calls due to the numerical noise when solving the equation `Hx + g = 0` near singularity. If the system has multiple possible minimum, it can happen that the small errors at beginning end up with different local minimum. It is severe on difficult systems.

In my experience, reducing orbital rotation stepsize can help to reduce the instability. However, this increases the possibility the solver stop at local minimum early. The first order algorithm (such as DIIS in ORCA) should not have this issue since the orbitals generated by diagonalization are almost deterministic. I'm not sure why the second order algorithm in Molpro does not have this issue. Other tricks might be used in their implementation

**Comment by ssh2** [comment] 2021-04-27 12:54
Qiming, thanks for an detailed reply. I think we understand this problem better now. The good news is that there are ways to diagnose it and avoid if necessary. I'm closing this issue for now.

**Closed by ssh2** 2021-04-27 12:54 UTC
