### ISSUE TITLE
Installation of PySCF - OSError

### ISSUE THREAD

**Issue by pwkj** [pyscf/pyscf#1511] opened 2022-11-11 20:41 UTC
Hello 

I have a problem with the installation of pyscf. I have used pyscf for some time now, and this is the first time I encounter this problem with the installation. My suspicion is that the error came after I upgraded my Mac to Ventura 13.0. 

I installed pyscf in my conda environment as `pip install pyscf`. When I type `import pyscf` in Python, I receive the error message shown in the attached picture _import_pyscf_. The error seems to be explained in https://pyscf.org/install.html under OSError ..., where it says the error is caused by the incorrect RPATH. To solve the problem, I should `cd pyscf/lib` and run `sh _runme_to_fix_dylib_osx10.11.sh`. The problem is I don’t have the _runme_to_fix_dylib_osx10.11.sh file in pyscf/lib? I have attached a picture _pyscf_lib_ showing all the files in the pyscf/lib folder. 

I appreciate the help 

Best
Phillip
 
![pyscf_lib](https://user-images.githubusercontent.com/46899159/201426884-2e3e2f61-8261-44e6-a09d-3b78a3984214.png)
![import_pyscf](https://user-images.githubusercontent.com/46899159/201426888-d32eec1c-cae3-4b22-a4e8-d98df8795d52.png)

**Comment by pwkj** [comment] 2022-11-11 21:21
I did `brew install libomp` but still it doesn't work.

**Comment by jamesETsmith** [comment] 2022-11-11 21:58
@pwkj, do you have an M1/M2 based mac? Just as a heads up this also looks like a duplicate of #1469. I no longer have a mac so I can't test anything locally. My two suggestions would be:

1. (Easiest) make sure that your `brew` installed `libomp.dylib` is in your `DYLD_LIBRARY_PATH`, `brew` may have installed it somewhere outside of your default library path
2. (Easier) try building from source with `pip install git+https://github.com/pyscf/pyscf` inside your conda env and don't worry about specifying compilers
3. (Harder) try building from source using `brew` or `conda` installed compilers, see instructions [here](https://pyscf.org/install.html#compiling-from-source-code) and [here](https://github.com/pyscf/pyscf/issues/1015#issuecomment-880671872).

**Comment by pwkj** [comment] 2022-11-11 22:25
@jamesETsmith, thank you for your reply. 

My mac is a M1. 

I just tried the `pip install git+https://github.com/pyscf/pyscf` but I receive the error:

<img width="1356" alt="Screenshot 2022-11-11 at 5 24 13 PM" src="https://user-images.githubusercontent.com/46899159/201439137-1dadfa30-9249-45c4-9d67-efe8fcd15181.png">

**Comment by pwkj** [comment] 2022-11-14 14:58
@jamesETsmith now it works using the `pip install git+https://github.com/pyscf/pyscf`! I really appreciate the help James. Why `pip install pyscf` is not working for me is still an unsolved problem, but for now I can run pyscf which is the most important.

**Comment by jamesETsmith** [comment] 2022-11-14 15:02
@pwkj glad that worked! I'm sorry we weren't able to fix your original problem, but I'm glad we got things working

**Comment by verena-neufeld** [comment] 2024-01-10 20:06
Hi @pwkj thanks for your question! @sunqm is this resolved by now (you added the help wanted flag) and if no, what needs to be done?

**Comment by sunqm** [comment] 2024-08-17 22:17
Pip wheels have been built and released for apple sillicon archs since pyscf-2.4 .

**Closed by sunqm** 2024-08-17 22:17 UTC
