### ISSUE TITLE
Computing analytic first and second derivatives of electron integrals, with respect to nuclear coordinates?

### ISSUE THREAD

**Issue by Lucaman99** [pyscf/pyscf#992] opened 2021-06-22 13:25 UTC
Is it possible to compute analytic first and second order derivatives with respect to nuclear coordinates of the one and two-electron integrals:

![Screen Shot 2021-06-22 at 9 24 56 AM](https://user-images.githubusercontent.com/29210432/122932433-ba79ae80-d33b-11eb-9210-f11d4c0ab26e.png)

using PySCF functionality?

**Comment by fishjojo** [comment] 2021-06-22 19:20
You can take a look at `pyscf/grad/rhf.py` and `pyscf/hessian/rhf.py`, which have the derivatives of these integrals.

**Comment by Lucaman99** [comment] 2021-06-22 19:22
Thanks for the reply @fishjojo, I did take a look in those files, and it wasn't totally clear to me which methods are computing these derivatives. Do you happen to know precisely which methods these would be?

**Comment by fishjojo** [comment] 2021-06-23 21:04
`hcore_generator` will generate a function which can compute the derivatives of the one-body terms with respect to the nuclear coordinates of the specified atoms. We usually don't compute the full nuclear derivative of the two-electron integral, but the pieces to construct that are available. `mol.intor("int2e_ip1")` gives (\nabla \phi_p \phi_q | \phi_r \phi_s). For hessian, you need "int2e_ipip1", "int2e_ipvip1", and "int2e_ip1ip2". The definitions of these integrals are given in pyscf/gto/moleintor.py.

**Comment by fishjojo** [comment] 2021-10-06 00:28
Duplicate of #1067

**Comment by alexm-gc** [comment] 2022-11-07 17:16
> "it wasn't totally clear to me which methods are computing these derivatives."
The derivatives are computed by calling `libcint` it's not done in python, so you'll only be able to see the library call.

**Closed** 2023-03-17 01:31 UTC
