### ISSUE TITLE
Broken-symmetry DFT example with meta-GGA

### ISSUE THREAD

**Issue by RagnarB83** [pyscf/pyscf#538] opened 2020-03-04 21:33 UTC
When I run the broken-symmetry DFT example (32-broken_symmetry_dft.py) with the meta-GGA functional TPSS instead of BP86  I get a Valueerror:
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs

**Comment by fishjojo** [comment] 2020-03-05 00:44
I couldn't reproduce the error with the latest release.

**Comment by RagnarB83** [comment] 2020-03-05 11:07
Just tried the latest release and the problem remains.
However I realized that I had also changed the basis set in the example.

So making the following changes to example 32-broken_symmetry_dft.py  : 
mol.basis = 'dzp' => mol.basis = 'def2-SVP'
mf.xc = 'bp86' => mf.xc = 'tpss'   (in two places of the input script!)

gives me the ValueError. It does not happen when doing the functional change alone or doing the basis set change alone.
Truly weird.

**Comment by sunqm** [comment] 2020-03-06 03:46
Tpss is not robust enough in libxc the default dft functional library in my
experience. For meta gga, fine grids are often needed to produce reasonable
results. Not sure whether this is the cause. You can try xcfun as shown in
example/dft/32 . If xcfun works, we may consider to report this problem to
libxc developers

**Comment by sunqm** [comment] 2020-03-07 21:28
Switching to xcfun does not solve the nan problem. Seems the tpss functional needs certain restrictions on the density matrix

**Comment by fishjojo** [comment] 2020-03-11 21:32
The problem is that the spin density becomes negative after manually switching the local alpha and beta density matrices in the example. This may happen for other functionals and basis sets.

**Comment by susilehtola** [comment] 2020-03-15 21:39
https://gitlab.com/libxc/libxc/-/issues/152

**Comment by hyllios** [comment] 2020-03-16 09:45
Could you please send to libxc the values of the density/gradient/laplacian/tau that yield the NaN?

**Comment by susilehtola** [comment] 2020-03-17 09:34
Patch for PySCF to extract NaNs for metaGGAs
[pyscf_libxc.patch.txt](https://github.com/pyscf/pyscf/files/4342577/pyscf_libxc.patch.txt)

There's a bunch of NaNs in the output
```
NaN encountered: rho = ( 6.111485e-09,  8.461480e-07), sigma = ( 1.922368e-15, -3.273359e-14), tau = ( 1.218390e-12, -3.790241e-10), lapl = ( 1.938263e-07, -nan) -> vrho = (-2.084215e-02, -nan), vsigma = ( 0.000000e+00, -5.678782e+01), tau = (-nan,  6.810752e-10), lapl = (-2.717539e-03, -2.459632e-03)
```
but the weird thing is that 

1) you see them in the density laplacian(!) and that
2) the laplacian potential is non-zero even though I don't think TPSS depends on the Laplacian...

**Comment by susilehtola** [comment] 2020-03-18 02:01
The calculation works with libxc master (soon to be libxc 5) thanks to patches by @hyllios.

**Comment by fishjojo** [comment] 2021-10-05 19:58
Fixed with libxc 5. Closing.

**Closed by fishjojo** 2021-10-05 19:58 UTC
Labels: help wanted
