### ISSUE TITLE
Proposed Solutions for MO Randomness

### ISSUE THREAD

**Issue by galena01** [pyscf/pyscf#2243] opened 2024-06-03 02:18 UTC
When calculating MO coefficients, PySCF can produce random results, which are not influenced by random number seeds. Although random MO coefficients do not affect the final SCF energy, they can have an indeterminate impact on downstream tasks (such as the calculation of electron integrals, Jordan-Wigner mapping, etc.), thus affecting the reproducibility of the entire program. This issue has been raised multiple times in issues #580, #1449, and #1458. Therefore, I suggest adding a method to obtain stable MO coefficients in the documentation.

Based on my observations, the randomness in the program originates from the following function:
https://github.com/pyscf/pyscf/blob/cdadc11a4494cb0aa42c2e408856759eca0a0efa/pyscf/lib/vhf/nr_incore.c#L624C1-L625C60
As Garnet mentioned in #580, the addition of floating-point numbers can lead to rounding errors on the order of several times the machine epsilon due to different thread execution orders. This error enters into vhf and is magnified when solving the Roothaan equations due to the instability of the problem, leading to random results when MOs are nearly degenerate.

A simple solution is to modify the diagonalization function by rounding the matrix h before diagonalization, thus preventing the propagation of tiny errors:

```python
from pyscf import gto
mol = gto.M("N 0 0 0; N 0 0 1.2;", "sto3g")
mf = mol.RHF()
def round_eig(f):
    return lambda h, s: f(h.round(12), s)
mf.eig = round_eig(mf.eig)
mf.kernel()
print(mf.mo_coeff)
```

This code snippet can produce consistent molecular orbital coefficients that are not affected by random errors. Considering that using PySCF to obtain electron integrals is a common use case, I believe it would be beneficial to include this approach in the section on 1- and 2-Electron Integrals.

**Comment by 1234zou** [comment] 2024-06-27 12:07
I have a question here: in HF/DFT, for any two orbitals which have the same orbital energies, any unitary transformations on these degenerate orbitals are equivalent SCF solutions. This is the intrinsic nature of quantum mechanics and linear algebra, which makes the MO coefficients not unique on these orbitals. I do not understand how you/what's your plan to avoid this problem?

**Comment by susilehtola** [comment] 2024-06-27 12:42
> I have a question here: in HF/DFT, for any two orbitals which have the same orbital energies, any unitary transformations on these degenerate orbitals are equivalent SCF solutions. This is the intrinsic nature of quantum mechanics and linear algebra, which makes the MO coefficients not unique on these orbitals. I do not understand how you/what's your plan to avoid this problem?

HF/DFT is invariant to unitary transformations of *any* occupied orbitals. The energy *does* depend on transformations between occupied and unoccupied orbitals.

The problem here is that strongly correlated systems have pretty much by definition several local minima for HF. Since the system is thus ill-behaved, there is no guarantee that the result is reproducible in the presence of finite precision algebra.

My suggestion would be to switch to e.g. LDA orbitals, as DFT is less susceptible to local minima for such systems.

**Comment by 1234zou** [comment] 2024-06-27 12:58
If we are actually talking about multiple SCF solutions (with different energies, orbital energies, etc), I agree that we should use CASSCF. UNO(or its localized one) obtained from different UHF energies usually lead to one common CASSCF energy.

**Comment by sunqm** [comment] 2024-07-08 05:22
I'll close this issue because this suggestion will not be able to completely remove the uncertainty of phase in degenerated orbitals. Please feel free to continue the discussion.

**Closed by sunqm** 2024-07-08 05:22 UTC
