### ISSUE TITLE
DIIS fails to converge triplet O in cc-pVDZ

### ISSUE THREAD

**Issue by susilehtola** [pyscf/pyscf#1524] opened 2022-11-29 09:52 UTC
The oxygen 3P wave function cannot be converged even in cc-pVDZ with DIIS. Without DIIS the calculation works.
```
import pyscf

mol = pyscf.M(
    atom = 'O',
    spin = 2,
    basis = 'cc-pVDZ',
    symmetry = True,
    verbose = 4)

# This fails                                                                                                                                                                                  
mf = mol.ROHF()
mf.init_guess = '1e'
mf.irrep_nelec = {'s+0' : (2,2), 'p-1' : (1,0), 'p+0' : (1,0), 'p+1' : (1,1) }
mf.kernel()

# This works                                                                                                                                                                                  
mf = mol.ROHF()
mf.init_guess = '1e'
mf.irrep_nelec = {'s+0' : (2,2), 'p-1' : (1,0), 'p+0' : (1,0), 'p+1' : (1,1) }
mf.diis = None
mf.kernel()
```

**Comment by sunqm** [comment] 2023-03-20 22:38
Problem is caused by the numerical noise in symmetry forbidden elements. Fixed in PR #1638

**Closed by sunqm** 2023-03-20 22:38 UTC
