### ISSUE TITLE
Getting a lower bound for the ground state energy of a system

### ISSUE THREAD

**Issue by PabloAMC** [pyscf/pyscf#902] opened 2021-04-13 12:36 UTC
I am trying to find a relatively efficient way of calculating a lower bound of the ground state energy of a given molecule. I have found nothing implemented, but this article https://pubs.acs.org/doi/full/10.1021/acs.jctc.9b00128 has some ideas of how it could be done.
Am I missing something and this is easier to estimate than implementing a whole new method?
Thanks!

**Comment by sunqm** [comment] 2021-04-16 17:42
Are you considering to improve DMRG solver with this low bound algorithm?

**Comment by ajz34** [comment] 2021-04-30 05:33
I'm not familiar to this topic, so I'm not sure whether following comments would help :joy:

One possible way finding lower bound to the full CI energy (with given limited basis) is variational 2-RDM approach, which is stated in [QChem document](https://manual.q-chem.com/5.3/subsec_v2rdm_intro.html). The idea behind is possibly that Hilbert space formed by 2-RDM is slightly larger than CI space, and then the variational energy in a larger space should be lower to the full-CI energy. I didn't actually tried or learned this method, and is not related to the JCTC article mentioned.

I previously found the JCTC article (10.1021/acs.jctc.9b00128) for a course homework as TA, and successfully ploted the blue dotted line (Temple's method) in Figure 1 (a) therein (red dashed line is too hard for me to reproduce :crying_cat_face:).
What appears tricky and wired to me is that, this method 
- Requires information of first-excitation energy (maybe could be approximated by TD-HF or CASSCF).
- Stacks two hamiltonian to evaluate 〈φ|H^2|φ〉 (σ0 and σ1 in eq 16); may be this term is rarely evaluated. Maybe this is the most difficult part.

Additionally, when I want to implement Temple's method (not the improved version) to one-dimension box model system of length *l* (using even parity polynomial functions as basis, since ϕ(*x*) = *x*(*x*-*l*) is pretty similar to the real ground state φ(*x*) = sin(π*x*/*l*)), then 〈ϕ|H^2|ϕ〉 is simply zero if ϕ is quadratic/quartic polynomial. H|ϕ〉 could be ill-defined wavefunction (zero if ϕ is quadratic or non-continuous if ϕ is quartic). So I'm not sure whether Temple's method is sensitive to basis space.

**Comment by sunqm** [comment] 2023-03-22 08:24
I'll close this issue since nobody follows up this topic. Feel free to reopen it

**Closed by sunqm** 2023-03-22 08:24 UTC
