### ISSUE TITLE
time.clock has been deprecated and removed in python 3.8 in favor of time.perf_counter/process_time

### ISSUE THREAD

**Issue by tirkarthi** [pyscf/pyscf#702] opened 2020-09-15 15:12 UTC
Ref : https://github.com/python/cpython/pull/13270

```
pyscf/lib/logger.py:>>> t0 = time.clock()
pyscf/lib/logger.py:    time.clock = time.process_time
pyscf/lib/logger.py:        rec._t0, rec._w0 = time.clock(), time.time()
pyscf/lib/logger.py:        rec._t0 = time.clock()
pyscf/lib/logger.py:        rec._t0, rec._w0 = time.clock(), time.time()
pyscf/lib/logger.py:        rec._t0 = time.clock()
pyscf/lib/logger.py:        self._t0 = time.clock()
pyscf/lo/boys.py:    cput0 = (time.clock(), time.time())
pyscf/df/grad/uks.py:    t0 = (time.clock(), time.time())
pyscf/df/grad/rks.py:    t0 = (time.clock(), time.time())
pyscf/df/df.py:        t0 = (time.clock(), time.time())
pyscf/df/outcore.py:    time0 = (time.clock(), time.time())
pyscf/df/outcore.py:    time0 = (time.clock(), time.time())
pyscf/df/outcore.py:    time0 = (time.clock(), time.time())
pyscf/df/df_jk.py:    t0 = t1 = (time.clock(), time.time())
pyscf/df/df_jk.py:    t0 = t1 = (time.clock(), time.time())
pyscf/df/df_jk.py:    t0 = (time.clock(), time.time())
pyscf/df/incore.py:    t0 = (time.clock(), time.time())
pyscf/df/incore.py:    t0 = (time.clock(), time.time())
pyscf/df/hessian/uks.py:    time0 = t1 = (time.clock(), time.time())
pyscf/df/hessian/rhf.py:    time0 = t1 = (time.clock(), time.time())
pyscf/df/hessian/uhf.py:    time0 = t1 = (time.clock(), time.time())
pyscf/df/hessian/rks.py:    time0 = t1 = (time.clock(), time.time())
pyscf/ao2mo/semi_incore.py:    cput0 = time.clock(), time.time()
pyscf/ao2mo/semi_incore.py:    cput1 = time.clock(), time.time()
pyscf/ao2mo/outcore.py:    time_0pass = (time.clock(), time.time())
pyscf/ao2mo/outcore.py:                    ti1 = (time.clock(), time.time())
pyscf/ao2mo/outcore.py:    time0 = (time.clock(), time.time())
pyscf/ao2mo/outcore.py:    print(time.clock())
pyscf/ao2mo/outcore.py:    print(time.clock())
pyscf/ao2mo/outcore.py:    print(time.clock())
pyscf/ao2mo/outcore.py:    print(time.clock())
pyscf/ao2mo/test/bz_nr.py:print(time.clock())
pyscf/ao2mo/test/bz_nr.py:print(time.clock())
pyscf/ao2mo/test/bz_nr.py:print(time.clock())
pyscf/ao2mo/r_outcore.py:    time_0pass = (time.clock(), time.time())
pyscf/ao2mo/r_outcore.py:            ti1 = (time.clock(), time.time())
pyscf/ao2mo/r_outcore.py:    time0 = (time.clock(), time.time())
pyscf/ao2mo/r_outcore.py:    print(time.clock())
pyscf/ao2mo/r_outcore.py:    print(time.clock())
pyscf/ao2mo/incore.py:    print(time.clock())
pyscf/ao2mo/incore.py:    print(time.clock())
pyscf/sgx/sgx_jk.py:    t0 = time.clock(), time.time()
pyscf/sgx/sgx_jk.py:            tnuc = tnuc[0] - time.clock(), tnuc[1] - time.time()
pyscf/sgx/sgx_jk.py:            tnuc = tnuc[0] + time.clock(), tnuc[1] + time.time()
pyscf/sgx/sgx_jk.py:            tnuc = tnuc[0] - time.clock(), tnuc[1] - time.time()
pyscf/sgx/sgx_jk.py:            tnuc = tnuc[0] + time.clock(), tnuc[1] + time.time()
pyscf/sgx/sgx_jk.py:    t0 = time.clock(), time.time()
pyscf/sgx/sgx_jk.py:            tnuc = tnuc[0] - time.clock(), tnuc[1] - time.time()
pyscf/sgx/sgx_jk.py:            tnuc = tnuc[0] + time.clock(), tnuc[1] + time.time()
pyscf/sgx/sgx_jk.py:            tnuc = tnuc[0] - time.clock(), tnuc[1] - time.time()
pyscf/sgx/sgx_jk.py:            tnuc = tnuc[0] + time.clock(), tnuc[1] + time.time()
pyscf/sgx/sgx_jk.py:    Ktime = (time.clock(), time.time())
pyscf/eph/rhf.py:    cput0 = (time.clock(), time.time())
pyscf/mp/mp2.py:    cput1 = cput0 = (time.clock(), time.time())
pyscf/mp/mp2.py:    time0 = (time.clock(), time.time())
pyscf/mp/mp2.py:    time0 = (time.clock(), time.time())
pyscf/mp/gmp2.py:    cput0 = (time.clock(), time.time())
pyscf/mp/ump2.py:    time0 = (time.clock(), time.time())
pyscf/mp/ump2.py:    time0 = (time.clock(), time.time())
pyscf/geomopt/berny_solver.py:    t0 = time.clock(), time.time()
pyscf/scf/dhf.py:        t0 = (time.clock(), time.time())
pyscf/scf/dhf.py:        cput0 = (time.clock(), time.time())
pyscf/scf/cphf.py:    t0 = (time.clock(), time.time())
pyscf/scf/cphf.py:    t0 = (time.clock(), time.time())
pyscf/scf/ucphf.py:    t0 = (time.clock(), time.time())
pyscf/scf/ucphf.py:    t0 = (time.clock(), time.time())
pyscf/scf/hf.py:    cput0 = (time.clock(), time.time())
pyscf/scf/hf.py:        cput0 = (time.clock(), time.time())
pyscf/scf/hf.py:        cpu0 = (time.clock(), time.time())
pyscf/ci/cisd.py:    time0 = time.clock(), time.time()
pyscf/ci/gcisd.py:        time0 = time.clock(), time.time()
pyscf/icmpspt/icmpspt.py:    time0 = (time.clock(), time.time())
pyscf/icmpspt/icmpspt.py:    time1 = [time.clock(), time.time()]
pyscf/dmrgscf/nevpt_mpi.py:    t0 = (time.clock(), time.time())
pyscf/dmrgscf/nevpt_mpi.py:    t0 = (time.clock(), time.time())
pyscf/grad/tduhf.py:    time0 = time.clock(), time.time()
pyscf/grad/mp2.py:    time0 = time.clock(), time.time()
pyscf/grad/uks.py:    t0 = (time.clock(), time.time())
pyscf/grad/ump2.py:    time0 = time.clock(), time.time()
pyscf/grad/ccsd.py:    time0 = time.clock(), time.time()
pyscf/grad/ccsd.py:    time1 = time.clock(), time.time()
pyscf/grad/dhf.py:    t0 = (time.clock(), time.time())
pyscf/grad/dhf.py:        cput0 = (time.clock(), time.time())
pyscf/grad/tduks.py:    time0 = time.clock(), time.time()
pyscf/grad/uccsd.py:    time0 = time.clock(), time.time()
pyscf/grad/uccsd.py:    time1 = time.clock(), time.time()
pyscf/grad/rhf.py:    t0 = (time.clock(), time.time())
pyscf/grad/rhf.py:        cpu0 = (time.clock(), time.time())
pyscf/grad/rhf.py:        cput0 = (time.clock(), time.time())
pyscf/grad/tdrks.py:    time0 = time.clock(), time.time()
pyscf/grad/casscf.py:    time0 = time.clock(), time.time()
pyscf/grad/casci.py:    time0 = time.clock(), time.time()
pyscf/grad/uhf.py:    t0 = (time.clock(), time.time())
pyscf/grad/tdrhf.py:    time0 = time.clock(), time.time()
pyscf/grad/rks.py:    t0 = (time.clock(), time.time())
pyscf/adc/uadc.py:    cput0 = (time.clock(), time.time())
pyscf/tdscf/uks.py:        cpu0 = (time.clock(), time.time())
pyscf/tdscf/rhf.py:        cpu0 = (time.clock(), time.time())
pyscf/tdscf/rhf.py:        cpu0 = (time.clock(), time.time())
pyscf/tdscf/uhf.py:        cpu0 = (time.clock(), time.time())
pyscf/tdscf/uhf.py:        cpu0 = (time.clock(), time.time())
pyscf/tdscf/rks.py:        cpu0 = (time.clock(), time.time())
pyscf/gw/gw.py:        cput0 = (time.clock(), time.time())
pyscf/gw/gw.py:    cput0 = (time.clock(), time.time())
pyscf/gw/gw.py:    cput0 = (time.clock(), time.time())
pyscf/fci/direct_spin0.py:    print('t',time.clock())
pyscf/dft/uks.py:    t0 = (time.clock(), time.time())
pyscf/dft/numint.py:    print(time.clock())
pyscf/dft/numint.py:    print(time.clock())
pyscf/dft/dks.py:    t0 = (time.clock(), time.time())
pyscf/dft/gks.py:    t0 = (time.clock(), time.time())
pyscf/dft/rks.py:    t0 = (time.clock(), time.time())
pyscf/dft/rks.py:    t0 = (time.clock(), time.time())
pyscf/dft/r_numint.py:    print(time.clock())
pyscf/dft/r_numint.py:    print(time.clock())
pyscf/gto/ft_ao.py:    print(time.clock())
pyscf/gto/ft_ao.py:    print(time.clock())
pyscf/gto/ft_ao.py:    print(time.clock())
pyscf/gto/mole.py:        logger.info(self, 'CPU time: %12.2f', time.clock())
pyscf/x2c/x2c.py:        t0 = (time.clock(), time.time())
pyscf/mrpt/nevpt2.py:        time0 = (time.clock(), time.time())
pyscf/mrpt/nevpt2.py:    time0 = (time.clock(), time.time())
pyscf/mrpt/nevpt2.py:    time1 = [time.clock(), time.time()]
pyscf/prop/nsr/rhf.py:        cput0 = (time.clock(), time.time())
pyscf/prop/nmr/dhf.py:    t0 = (time.clock(), time.time())
pyscf/prop/nmr/dhf.py:        cput0 = (time.clock(), time.time())
pyscf/prop/nmr/dhf.py:        t0 = (time.clock(), time.time())
pyscf/prop/nmr/rhf.py:    cput1 = (time.clock(), time.time())
pyscf/prop/nmr/rhf.py:        cput0 = (time.clock(), time.time())
pyscf/prop/nmr/uhf.py:    cput1 = (time.clock(), time.time())
pyscf/prop/magnetizability/rhf.py:    cput1 = (time.clock(), time.time())
pyscf/prop/magnetizability/rhf.py:        cput0 = (time.clock(), time.time())
pyscf/prop/magnetizability/uhf.py:    cput1 = (time.clock(), time.time())
pyscf/prop/ssc/dhf.py:    cput1 = (time.clock(), time.time())
pyscf/prop/ssc/dhf.py:        cput0 = (time.clock(), time.time())
pyscf/prop/ssc/rhf.py:    cput1 = (time.clock(), time.time())
pyscf/prop/ssc/rhf.py:    cput1 = (time.clock(), time.time())
pyscf/prop/ssc/rhf.py:        cput0 = (time.clock(), time.time())
pyscf/prop/ssc/uhf.py:    cput1 = (time.clock(), time.time())
pyscf/prop/ssc/uhf.py:    cput1 = (time.clock(), time.time())
pyscf/prop/ssc/uhf.py:        cput0 = (time.clock(), time.time())
pyscf/prop/gtensor/uhf.py:        cput0 = (time.clock(), time.time())
pyscf/prop/zfs/uhf.py:    cput1 = (time.clock(), time.time())
pyscf/prop/zfs/uhf.py:        cput0 = (time.clock(), time.time())
pyscf/prop/rotational_gtensor/rhf.py:        cput0 = (time.clock(), time.time())
pyscf/prop/hfc/uhf.py:        cput0 = (time.clock(), time.time())
pyscf/prop/polarizability/rhf.py:    t0 = (time.clock(), time.time())
pyscf/prop/polarizability/rhf.py:    t0 = (time.clock(), time.time())
pyscf/prop/polarizability/uhf.py:    t0 = (time.clock(), time.time())
pyscf/soscf/newton_ah.py:    t3m = (time.clock(), time.time())
pyscf/soscf/newton_ah.py:    cput0 = (time.clock(), time.time())
pyscf/soscf/newton_ah.py:        cput0 = (time.clock(), time.time())
pyscf/soscf/ciah.py:    t2m = (time.clock(), time.time())
pyscf/mcscf/ucasci.py:    t0 = (time.clock(), time.time())
pyscf/mcscf/umc2step.py:    cput0 = (time.clock(), time.time())
pyscf/mcscf/mc1step.py:    t3m = (time.clock(), time.time())
pyscf/mcscf/mc1step.py:                t3m = (time.clock(), time.time())
pyscf/mcscf/mc1step.py:    cput0 = (time.clock(), time.time())
pyscf/mcscf/umc_ao2mo.py:    time0 = (time.clock(), time.time())
pyscf/mcscf/umc_ao2mo.py:    time1 = [time.clock(), time.time()]
pyscf/mcscf/umc_ao2mo.py:    time1 = [time.clock(), time.time()]
pyscf/mcscf/mc_ao2mo.py:    time0 = (time.clock(), time.time())
pyscf/mcscf/df.py:            t1 = t0 = (time.clock(), time.time())
pyscf/mcscf/df.py:        t1 = t0 = (time.clock(), time.time())
pyscf/mcscf/casci.py:    t0 = (time.clock(), time.time())
pyscf/mcscf/umc1step.py:    cput0 = (time.clock(), time.time())
pyscf/mcscf/newton_casscf.py:    cput0 = (time.clock(), time.time())
pyscf/mcscf/mc2step.py:    cput0 = (time.clock(), time.time())
pyscf/pbc/lib/linalg_helper.py:    cput1 = (time.clock(), time.time())
pyscf/pbc/df/mdf.py:    t1 = (time.clock(), time.time())
pyscf/pbc/df/df.py:    t1 = (time.clock(), time.time())
pyscf/pbc/df/df.py:            t1 = (time.clock(), time.time())
pyscf/pbc/df/aft_jk.py:    t1 = (time.clock(), time.time())
pyscf/pbc/df/aft_jk.py:    t1 = (time.clock(), time.time())
pyscf/pbc/df/aft_jk.py:    t1 = (time.clock(), time.time())
pyscf/pbc/df/aft.py:    t0 = t1 = (time.clock(), time.time())
pyscf/pbc/df/df_jk.py:    t1 = (time.clock(), time.time())
pyscf/pbc/df/df_jk.py:    t1 = (time.clock(), time.time())
pyscf/pbc/df/df_jk.py:    t1 = (time.clock(), time.time())
pyscf/pbc/df/fft_jk.py:    t1 = (time.clock(), time.time())
pyscf/pbc/df/fft_jk.py:    t1 = (time.clock(), time.time())
pyscf/pbc/scf/khf.py:        cpu0 = (time.clock(), time.time())
pyscf/pbc/scf/hf.py:        cpu0 = (time.clock(), time.time())
pyscf/pbc/ci/kcis_rhf.py:    cpu0 = (time.clock(), time.time())
pyscf/pbc/ci/kcis_rhf.py:    cpu1 = (time.clock(), time.time())
pyscf/pbc/ci/kcis_rhf.py:    cpu0 = (time.clock(), time.time())
pyscf/pbc/ci/kcis_rhf.py:        cput0 = (time.clock(), time.time())
pyscf/pbc/ci/kcis_rhf.py:                cput1 = time.clock(), time.time()
pyscf/pbc/ci/kcis_rhf.py:    cput0 = (time.clock(), time.time())
pyscf/pbc/grad/kuks.py:    t0 = (time.clock(), time.time())
pyscf/pbc/grad/krks.py:    t0 = (time.clock(), time.time())
pyscf/pbc/grad/krhf.py:    t0 = (time.clock(), time.time())
pyscf/pbc/grad/krhf.py:        cpu0 = (time.clock(), time.time())
pyscf/pbc/grad/krhf.py:        cpu0 = (time.clock(), time.time())
pyscf/pbc/grad/krhf.py:        cpu0 = (time.clock(), time.time())
pyscf/pbc/grad/krhf.py:        cput0 = (time.clock(), time.time())
pyscf/pbc/grad/kuhf.py:    t0 = (time.clock(), time.time())
pyscf/pbc/dft/kuks.py:    t0 = (time.clock(), time.time())
pyscf/pbc/dft/uks.py:    t0 = (time.clock(), time.time())
pyscf/pbc/dft/krks.py:    t0 = (time.clock(), time.time())
pyscf/pbc/dft/rks.py:    t0 = (time.clock(), time.time())
pyscf/pbc/x2c/sfx2c1e.py:    t1 = (time.clock(), time.time())
pyscf/pbc/prop/efg/rhf.py:    t0 = t1 = (time.clock(), time.time())
pyscf/pbc/mpicc/kccsd_rhf.py:    time0 = time.clock(), time.time()
pyscf/pbc/mpicc/kccsd_rhf.py:    cput1 = time.clock(), time.time()
pyscf/pbc/mpicc/kccsd_rhf.py:    cput2 = time.clock(), time.time()
pyscf/pbc/mpicc/kccsd_rhf.py:    cput2 = time.clock(), time.time()
pyscf/pbc/mpicc/kccsd_rhf.py:    cput2 = time.clock(), time.time()
pyscf/pbc/mpicc/kccsd_rhf.py:    cput2 = time.clock(), time.time()
pyscf/pbc/mpicc/kccsd_rhf.py:    cput2 = time.clock(), time.time()
pyscf/pbc/mpicc/kccsd_rhf.py:    cput2 = time.clock(), time.time()
pyscf/pbc/mpicc/kccsd_rhf.py:        time0 = time.clock(), time.time()
pyscf/pbc/mpicc/kccsd_rhf.py:        cput1 = time.clock(), time.time()
pyscf/pbc/mpicc/kccsd_rhf.py:        time0 = time.clock(), time.time()
pyscf/pbc/mpicc/kccsd_rhf.py:        time0 = time.clock(), time.time()
pyscf/pbc/mpicc/kccsd_rhf.py:        cput2 = time.clock(), time.time()
pyscf/pbc/mpicc/kccsd_rhf.py:        time0 = time.clock(), time.time()
pyscf/pbc/mpicc/kccsd_rhf.py:        cput2 = time.clock(), time.time()
pyscf/pbc/mpicc/kccsd_rhf.py:        time0 = time.clock(), time.time()
pyscf/pbc/mpicc/kccsd_rhf.py:        cput2 = time.clock(), time.time()
pyscf/pbc/mpicc/kccsd_rhf.py:        time0 = time.clock(), time.time()
pyscf/pbc/mpicc/kccsd_rhf.py:        cput0 = (time.clock(), time.time())
pyscf/pbc/mpicc/kccsd_rhf.py:            cput1 = time.clock(), time.time()
pyscf/pbc/mpicc/kccsd_rhf.py:            cput1 = time.clock(), time.time()
pyscf/pbc/cc/kccsd_uhf.py:    time0 = time.clock(), time.time()
pyscf/pbc/cc/kccsd_uhf.py:        time0 = time.clock(), time.time()
pyscf/pbc/cc/kccsd_uhf.py:    cput0 = (time.clock(), time.time())
pyscf/pbc/cc/kintermediates_rhf.py:    cpu1 = cpu0 = (time.clock(), time.time())
pyscf/pbc/cc/kintermediates_rhf.py:            cput2 = (time.clock(), time.time())
pyscf/pbc/cc/kccsd.py:    time0 = time.clock(), time.time()
pyscf/pbc/cc/kccsd.py:        time0 = time.clock(), time.time()
pyscf/pbc/cc/kccsd.py:    cput0 = (time.clock(), time.time())
pyscf/pbc/cc/kccsd.py:        cput0 = (time.clock(), time.time())
pyscf/pbc/cc/kccsd.py:        cput0 = (time.clock(), time.time())
pyscf/pbc/cc/kccsd.py:        cput0 = (time.clock(), time.time())
pyscf/pbc/cc/kccsd.py:        cput0 = (time.clock(), time.time())
pyscf/pbc/cc/eom_kccsd_rhf.py:    cput0 = (time.clock(), time.time())
pyscf/pbc/cc/eom_kccsd_rhf.py:    cput0 = (time.clock(), time.time())
pyscf/pbc/cc/eom_kccsd_rhf.py:    cput0 = (time.clock(), time.time())
pyscf/pbc/cc/eom_kccsd_rhf.py:    cput0 = (time.clock(), time.time())
pyscf/pbc/cc/eom_kccsd_rhf.py:        cput0 = (time.clock(), time.time())
pyscf/pbc/cc/eom_kccsd_rhf.py:        cput0 = (time.clock(), time.time())
pyscf/pbc/cc/eom_kccsd_rhf.py:        cput0 = (time.clock(), time.time())
pyscf/pbc/cc/eom_kccsd_rhf.py:        cput0 = (time.clock(), time.time())
pyscf/pbc/cc/eom_kccsd_rhf.py:        cput0 = (time.clock(), time.time())
pyscf/pbc/cc/eom_kccsd_rhf.py:        cput0 = (time.clock(), time.time())
pyscf/pbc/cc/eom_kccsd_rhf.py:        cput0 = (time.clock(), time.time())
pyscf/pbc/cc/eom_kccsd_rhf.py:        cput0 = (time.clock(), time.time())
pyscf/pbc/cc/eom_kccsd_ghf.py:    cput0 = (time.clock(), time.time())
pyscf/pbc/cc/eom_kccsd_ghf.py:    cput0 = (time.clock(), time.time())
pyscf/pbc/cc/eom_kccsd_ghf.py:        cput0 = (time.clock(), time.time())
pyscf/pbc/cc/eom_kccsd_ghf.py:        cput0 = (time.clock(), time.time())
pyscf/pbc/cc/eom_kccsd_ghf.py:        cput0 = (time.clock(), time.time())
pyscf/pbc/cc/eom_kccsd_ghf.py:        cput0 = (time.clock(), time.time())
pyscf/pbc/cc/eom_kccsd_ghf.py:        cput0 = (time.clock(), time.time())
pyscf/pbc/cc/eom_kccsd_ghf.py:        cput0 = (time.clock(), time.time())
pyscf/pbc/cc/kccsd_rhf.py:    time0 = time1 = time.clock(), time.time()
pyscf/pbc/cc/kccsd_rhf.py:        time0 = time.clock(), time.time()
pyscf/pbc/cc/kccsd_rhf.py:        cput0 = (time.clock(), time.time())
pyscf/pbc/cc/kccsd_rhf.py:            cput1 = time.clock(), time.time()
pyscf/pbc/cc/kccsd_rhf.py:            cput1 = time.clock(), time.time()
pyscf/pbc/cc/kccsd_rhf.py:            # cput1 = time.clock(), time.time()
pyscf/pbc/cc/kccsd_rhf.py:            cput1 = time.clock(), time.time()
pyscf/pbc/cc/kccsd_rhf.py:        cput0 = (time.clock(), time.time())
pyscf/pbc/cc/kccsd_rhf.py:        cput0 = (time.clock(), time.time())
pyscf/pbc/cc/kccsd_rhf.py:        cput0 = (time.clock(), time.time())
pyscf/pbc/cc/kccsd_rhf.py:        cput0 = (time.clock(), time.time())
pyscf/pbc/cc/eom_kccsd_uhf.py:        cput0 = (time.clock(), time.time())
pyscf/pbc/cc/eom_kccsd_uhf.py:        cput0 = (time.clock(), time.time())
pyscf/pbc/cc/eom_kccsd_uhf.py:        cput0 = (time.clock(), time.time())
pyscf/pbc/cc/kccsd_t_rhf.py:    cpu1 = cpu0 = (time.clock(), time.time())
pyscf/pbc/cc/kccsd_t_rhf_slow.py:    cpu1 = cpu0 = (time.clock(), time.time())
pyscf/solvent/_ddcosmo_tdscf_grad.py:    time0 = time.clock(), time.time()
pyscf/solvent/_ddcosmo_tdscf_grad.py:    time0 = time.clock(), time.time()
pyscf/solvent/_ddcosmo_tdscf_grad.py:    time0 = time.clock(), time.time()
pyscf/solvent/_ddcosmo_tdscf_grad.py:    time0 = time.clock(), time.time()
pyscf/cc/dfccsd.py:    time0 = time.clock(), time.time()
pyscf/cc/eom_uccsd.py:    time0 = time.clock(), time.time()
pyscf/cc/eom_uccsd.py:        cput0 = (time.clock(), time.time())
pyscf/cc/eom_uccsd.py:        cput0 = (time.clock(), time.time())
pyscf/cc/eom_uccsd.py:        cput0 = (time.clock(), time.time())
pyscf/cc/eom_uccsd.py:        cput0 = (time.clock(), time.time())
pyscf/cc/gccsd_lambda.py:    time0 = time.clock(), time.time()
pyscf/cc/gccsd.py:    cput0 = (time.clock(), time.time())
pyscf/cc/rccsd_lambda.py:    time0 = time.clock(), time.time()
pyscf/cc/ccsd.py:    cput1 = cput0 = (time.clock(), time.time())
pyscf/cc/ccsd.py:    time0 = time.clock(), time.time()
pyscf/cc/ccsd.py:    time1 = time.clock(), time.time()
pyscf/cc/ccsd.py:    time0 = time.clock(), time.time()
pyscf/cc/ccsd.py:    time0 = time.clock(), time.time()
pyscf/cc/ccsd.py:    time0 = time.clock(), time.time()
pyscf/cc/ccsd.py:    time0 = time.clock(), time.time()
pyscf/cc/ccsd.py:        time0 = time.clock(), time.time()
pyscf/cc/ccsd.py:    cput0 = (time.clock(), time.time())
pyscf/cc/ccsd.py:    cput0 = (time.clock(), time.time())
pyscf/cc/ccsd.py:    cput1 = time.clock(), time.time()
pyscf/cc/ccsd.py:    cput0 = (time.clock(), time.time())
pyscf/cc/ccsd_lambda.py:    cput0 = (time.clock(), time.time())
pyscf/cc/ccsd_lambda.py:    time0 = time.clock(), time.time()
pyscf/cc/ccsd_t.py:    cpu1 = cpu0 = (time.clock(), time.time())
pyscf/cc/ccsd_t.py:    cpu1 = (time.clock(), time.time())
pyscf/cc/uccsd_slow.py:        time0 = time.clock(), time.time()
pyscf/cc/uccsd_slow.py:        cput0 = (time.clock(), time.time())
pyscf/cc/uccsd_slow.py:            cput1 = time.clock(), time.time()
pyscf/cc/uccsd_slow.py:            cput1 = time.clock(), time.time()
pyscf/cc/uccsd_slow.py:        cput0 = (time.clock(), time.time())
pyscf/cc/uccsd_slow.py:        cput0 = (time.clock(), time.time())
pyscf/cc/uccsd_slow.py:        cput0 = (time.clock(), time.time())
pyscf/cc/uccsd_slow.py:        cput0 = (time.clock(), time.time())
pyscf/cc/eom_rccsd.py:    cput0 = (time.clock(), time.time())
pyscf/cc/eom_rccsd.py:    cpu1 = (time.clock(), time.time())
pyscf/cc/eom_rccsd.py:    cpu1 = (time.clock(), time.time())
pyscf/cc/eom_rccsd.py:        cput0 = (time.clock(), time.time())
pyscf/cc/eom_rccsd.py:        cput0 = (time.clock(), time.time())
pyscf/cc/eom_rccsd.py:        cput0 = (time.clock(), time.time())
pyscf/cc/eom_rccsd.py:        cput0 = (time.clock(), time.time())
pyscf/cc/eom_rccsd.py:        cput0 = (time.clock(), time.time())
pyscf/cc/eom_rccsd.py:        cput0 = (time.clock(), time.time())
pyscf/cc/eom_rccsd.py:        cput0 = (time.clock(), time.time())
pyscf/cc/rccsd_slow.py:        cput0 = (time.clock(), time.time())
pyscf/cc/rccsd_slow.py:        cput0 = (time.clock(), time.time())
pyscf/cc/rccsd_slow.py:        cput0 = (time.clock(), time.time())
pyscf/cc/rccsd_slow.py:        cput0 = (time.clock(), time.time())
pyscf/cc/rccsd_slow.py:        cput0 = (time.clock(), time.time())
pyscf/cc/rccsd_slow.py:        cput0 = (time.clock(), time.time())
pyscf/cc/rccsd_slow.py:        cput0 = (time.clock(), time.time())
pyscf/cc/eom_gccsd.py:        cput0 = (time.clock(), time.time())
pyscf/cc/eom_gccsd.py:        cput0 = (time.clock(), time.time())
pyscf/cc/eom_gccsd.py:        cput0 = (time.clock(), time.time())
pyscf/cc/eom_gccsd.py:        cput0 = (time.clock(), time.time())
pyscf/cc/eom_gccsd.py:        cput0 = (time.clock(), time.time())
pyscf/cc/eom_gccsd.py:        cput0 = (time.clock(), time.time())
pyscf/cc/uccsd_lambda.py:    time0 = time.clock(), time.time()
pyscf/cc/uccsd.py:    time0 = time.clock(), time.time()
pyscf/cc/uccsd.py:    time0 = time.clock(), time.time()
pyscf/cc/uccsd.py:    time0 = time.clock(), time.time()
pyscf/cc/uccsd.py:        time0 = time.clock(), time.time()
pyscf/cc/uccsd.py:    cput1 = time.clock(), time.time()
pyscf/cc/ccsd_rdm.py:    time1 = time.clock(), time.time()
pyscf/cc/ccsd_rdm.py:    time1 = time.clock(), time.time()
pyscf/cc/rccsd.py:    cput0 = (time.clock(), time.time())
pyscf/cc/rccsd.py:    cput0 = (time.clock(), time.time())
pyscf/cc/uccsd_t.py:    cpu1 = cpu0 = (time.clock(), time.time())
pyscf/cc/uccsd_t.py:    cpu2 = [time.clock(), time.time()]
pyscf/cc/uccsd_t.py:    cpu2 = [time.clock(), time.time()]
pyscf/cc/uccsd_t.py:    cpu1 = (time.clock(), time.time())
pyscf/hessian/uks.py:    time0 = t1 = (time.clock(), time.time())
pyscf/hessian/rhf.py:    time0 = t1 = (time.clock(), time.time())
pyscf/hessian/rhf.py:    time0 = t1 = (time.clock(), time.time())
pyscf/hessian/uhf.py:    time0 = t1 = (time.clock(), time.time())
pyscf/hessian/uhf.py:    time0 = t1 = (time.clock(), time.time())
pyscf/hessian/rks.py:    time0 = t1 = (time.clock(), time.time())
```

**Comment by sunqm** [comment] 2020-09-17 18:17
Duplicate of #368

**Comment by sunqm** [comment] 2020-09-17 18:58
For backward compatibility, time.clock and time.time are still used in the code. They are aliased to time.process_time and time.perf_counter if applicable

**Closed by sunqm** 2020-09-17 18:58 UTC
