### ISSUE TITLE
Problems with FCI in Dooh symmetry

### ISSUE THREAD

**Issue by susilehtola** [pyscf/pyscf#1517] opened 2022-11-22 11:52 UTC
I am trying to run some FCI calculations in Dooh symmetry. The following input
```
import numpy
from pyscf import gto, scf, fci

mol = gto.Mole()
# Singlet bond length 2.913
mol.build(
    atom = 'Li 0 0 0; Li 0 0 2.913',
    unit = 'angstrom',
    basis = 'cc-pVDZ',
    spin = 0,
    verbose = 4,
    symmetry = True,
    symmetry_subgroup = 'Dooh'
)
mf = scf.RHF(mol)
mf.kernel()

ci_energies = {}
for sym in ['A1g', 'A1u', 'E1ux', 'E1uy', 'E1gx', 'E1gy', 'E2gx', 'E2gy', 'E2ux', 'E2uy', 'E3ux', 'E3uy', 'E3gx', 'E3gy']:
    mci = fci.FCI(mol, mf.mo_coeff, singlet=False)
    mci.wfnsym = sym
    e, civec = mci.kernel(nroots=3)
    ci_energies[sym] = e
    print('{}: {}'.format(sym,e))
```
gives the following energies
```
A1g: [-14.90048097 -14.82656573 -14.80619407]
A1u: [-14.86012998 -14.83774646 -14.75794947]
E1ux: [-14.84879138 -14.80549729 -14.74183726]
E1uy: [-14.84879138 -14.80549729 -14.74183726]
E1gx: [-14.79618456 -14.78343722 -14.75798428]
E1gy: [-14.79618456 -14.78343722 -14.75798428]
E2gx: [-14.90048097 -14.82656573 -14.80619407]
E2gy: [-14.7461423  -14.74326066 -14.64015681]
E2ux: [-14.86012998 -14.83774646 -14.75794947]
E2uy: [-14.705979   -14.7043607  -14.66552235]
E3ux: [-14.84879138 -14.80549729 -14.74183726]
E3uy: [-14.84879138 -14.80549729 -14.74183726]
E3gx: [-14.79618456 -14.78343722 -14.75798428]
E3gy: [-14.79618456 -14.78343722 -14.75798428]
```
As you can see, there is a big problem in the E2 energies: 

- the x and y data are different
- `E2gx` results in the same energies as `A1g`
- `E2ux` results in the same energies as `A1u`
- the lowest Phi state `E3ux` is lower in energy than the Delta state `E2gy`

Running with `verbose=10` shows `Guessing CI wfn symmetry = 0` for the `E2gx` calculation (same as for the `A1g` calculation), while `E2ux` and `A1u` both show `Guessing CI wfn symmetry = 5`, so this could be just a problem with a wrong initial guess

**Comment by sunqm** [comment] 2022-11-23 23:14
It caused by the symmetry representation mapping https://github.com/pyscf/pyscf/blob/master/pyscf/symm/basis.py#L384  .
In the current fci implementation symmetry is filtered based on irreducible products of D2h symmetry.

**Comment by ndattani** [comment] 2022-11-26 13:17
@sunqm I think beyond just the D2h filtering, the FCI code (still?) doesn't support complex integrals, as mentioned in Issue #203. I was thinking that if FCI in D_infinity,h was too big of a coding leap, you could try something like D10h, with the following character table (note that the exact numbers are (√5+1)/2 and (√5-1)/2):

```
A1g     1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000 
A2g     1.0000  1.0000  1.0000  1.0000  1.0000  1.0000 -1.0000 -1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000 -1.0000 -1.0000
B1g     1.0000 -1.0000  1.0000 -1.0000  1.0000 -1.0000  1.0000 -1.0000  1.0000  1.0000 -1.0000  1.0000 -1.0000 -1.0000 -1.0000  1.0000
B2g     1.0000 -1.0000  1.0000 -1.0000  1.0000 -1.0000 -1.0000  1.0000  1.0000  1.0000 -1.0000  1.0000 -1.0000 -1.0000  1.0000 -1.0000 
E1g     2.0000  1.6180  0.6180 -0.6180 -1.6180 -2.0000  0.0000  0.0000  2.0000 -1.6180 -0.6180  0.6180  1.6180 -2.0000  0.0000  0.0000 
E2g     2.0000  0.6180 -1.6180 -1.6180  0.6180  2.0000  0.0000  0.0000  2.0000  0.6180 -1.6180 -1.6180  0.6180  2.0000  0.0000  0.0000 
E3g     2.0000 -0.6180 -1.6180  1.6180  0.6180 -2.0000  0.0000  0.0000  2.0000  0.6180  1.6180 -1.6180 -0.6180 -2.0000  0.0000  0.0000 
E4g     2.0000 -1.6180  0.6180  0.6180 -1.6180  2.0000  0.0000  0.0000  2.0000 -1.6180  0.6180  0.6180 -1.6180  2.0000  0.0000  0.0000 
A1u     1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000 -1.0000 -1.0000 -1.0000 -1.0000 -1.0000 -1.0000 -1.0000 -1.0000
A2u     1.0000  1.0000  1.0000  1.0000  1.0000  1.0000 -1.0000 -1.0000 -1.0000 -1.0000 -1.0000 -1.0000 -1.0000 -1.0000  1.0000  1.0000 
B1u     1.0000 -1.0000  1.0000 -1.0000  1.0000 -1.0000  1.0000 -1.0000 -1.0000 -1.0000  1.0000 -1.0000  1.0000  1.0000  1.0000 -1.0000 
B2u     1.0000 -1.0000  1.0000 -1.0000  1.0000 -1.0000 -1.0000  1.0000 -1.0000 -1.0000  1.0000 -1.0000  1.0000  1.0000 -1.0000  1.0000
E1u     2.0000  1.6180  0.6180 -0.6180 -1.6180 -2.0000  0.0000  0.0000 -2.0000  1.6180  0.6180 -0.6180 -1.6180  2.0000  0.0000  0.0000 
E2u     2.0000  0.6180 -1.6180 -1.6180  0.6180  2.0000  0.0000  0.0000 -2.0000 -0.6180  1.6180  1.6180 -0.6180 -2.0000  0.0000  0.0000 
E3u     2.0000 -0.6180 -1.6180  1.6180  0.6180 -2.0000  0.0000  0.0000 -2.0000 -0.6180 -1.6180  1.6180  0.6180  2.0000  0.0000  0.0000 
E4u     2.0000 -1.6180  0.6180  0.6180 -1.6180  2.0000  0.0000  0.0000 -2.0000  1.6180 -0.6180 -0.6180  1.6180 -2.0000  0.0000  0.0000 
```

However, this group is still non-Abelian, so it might take just about as much time to complete this all the way for the arbitrary case.

**Comment by verena-neufeld** [comment] 2024-01-04 19:40
Hi @susilehtola , thanks for posting! Has it been resolved by now?

**Comment by susilehtola** [comment] 2024-01-05 13:12
Unable to verify due to issue above

**Comment by susilehtola** [comment] 2024-01-31 12:24
Not much better
```
init E= -14.7936185905029
HOMO (A1g) = -0.155052406661151  LUMO (A1u) = -0.0241492222701659
cycle= 1 E= -14.8685692377365  delta_E= -0.075  |g|= 0.027  |ddm|= 0.591
HOMO (A1g) = -0.179706717782551  LUMO (A1u) = 0.00332419083136048
cycle= 2 E= -14.8695566343991  delta_E= -0.000987  |g|= 0.00958  |ddm|= 0.0607
HOMO (A1g) = -0.176197689510525  LUMO (A1u) = 0.00542287953479872
cycle= 3 E= -14.8697531174122  delta_E= -0.000196  |g|= 0.00141  |ddm|= 0.0368
HOMO (A1g) = -0.17574816104011  LUMO (A1u) = 0.00555895098126317
cycle= 4 E= -14.8697592392132  delta_E= -6.12e-06  |g|= 0.000186  |ddm|= 0.00871
HOMO (A1g) = -0.175813595635885  LUMO (A1u) = 0.00554637376488877
cycle= 5 E= -14.8697593351565  delta_E= -9.59e-08  |g|= 2.43e-05  |ddm|= 0.00142
HOMO (A1g) = -0.175812560952113  LUMO (A1u) = 0.00554648620831828
cycle= 6 E= -14.8697593368017  delta_E= -1.65e-09  |g|= 3.1e-06  |ddm|= 0.00021
HOMO (A1g) = -0.175812309371287  LUMO (A1u) = 0.0055477929941596
cycle= 7 E= -14.8697593368282  delta_E= -2.65e-11  |g|= 3.61e-07  |ddm|= 2.88e-05
HOMO (A1g) = -0.175811986178061  LUMO (A1u) = 0.005547865877198
Extra cycle  E= -14.8697593368284  delta_E= -2.77e-13  |g|= 1.3e-07  |ddm|= 1.51e-06
converged SCF energy = -14.8697593368284
Floating point exception (core dumped)
```

**Comment by sunqm** [comment] 2024-08-12 02:11
I'll close this issue since I cannot reproduce this problem in PySCF-2.6. Additionally, for the Dooh symmetry, the cylindrical symmetry solver is recommended, see https://github.com/pyscf/pyscf/blob/master/examples/fci/03-cylindrical_symmetry.py . Please feel free to reopen the issue.

**Closed by sunqm** 2024-08-12 02:11 UTC
