### ISSUE TITLE
running dft.rks(mol) gives SymAdaptedRKS object instead of KohnShamDFT object

### ISSUE THREAD

**Issue by anbonimus** [pyscf/pyscf#1555] opened 2023-01-03 15:48 UTC
So I ran dft.rsk(mol), then I need to convert it to a hf object since i need to use it to run ccsd, but then i got the error msg saying that SymAdaptedRKS object has no attribute to_hf(). But dft.rks() should give me a KohnShamDFT object right? how should I deal with this?

**Comment by hebrewsnabla** [comment] 2023-01-04 09:17
Could you provide a minimal working example of this issue?

**Comment by anbonimus** [comment] 2023-01-04 18:09
Hi this is the code Im running. So running RKS should give a KohnShamDFT
object, just like the example on github. But instead its giving me a
SymAdaptedRKS object, which does not have to_hf() function.

Ruiren

**Comment by fishjojo** [comment] 2023-01-04 22:08
You probably set `mol.symmetry` to `Ture`. You can set it to `False`.

**Comment by tberkel** [comment] 2023-01-04 22:23
You didn't successfully post your minimal working code. Can you try again? SymAdaptedRKS object should have a to_hf() method through inheritance. The below works fine for me.

```
import pyscf
from pyscf import dft

mol = pyscf.M(
    atom = 'H 0 0 0; F 0 0 1.1',  # in Angstrom
    basis = '631g',
    symmetry = True,
)

mf = dft.RKS(mol)
mf.xc = 'blyp'
mf.kernel()
mf.analyze()

myhf = mf.to_hf()
myhf.kernel()
myhf.analyze()
```

**Comment by tberkel** [comment] 2023-01-05 22:47
Your file attachments are not working, but I still can't reproduce your error. Here's a simplified version of your script, and this runs correctly for me, with the output below.
```
E(CCSD) = -107.1372410076296  E_corr = -0.2148240251663125
import pyscf
from pyscf import gto, dft, cc

print(pyscf.__version__)

mol = gto.Mole(
    atom = 'f;li 1 1.4',  # in Angstrom
    basis = 'ccpvdz', # smaller than ccpv5z for testing
    symmetry = True, # or False
)
mol.build(parse_arg=False)
mf = dft.RKS(mol)
mf.xc = 'b3lyp'
mf.kernel()
temp = mf.to_hf()

mycc = cc.CCSD(temp).run()

ecc_t = mycc.e_tot + mycc.ccsd_t()
```

```
2.1.1
converged SCF energy = -107.371151209161
E(CCSD) = -107.1372410076296  E_corr = -0.2148240251663125
CCSD(T) correction = -0.00366931623184919
```

**Comment by anbonimus** [comment] 2023-01-06 18:59
Thank you so much! My pyscf version was 2.0.1. I just updated it and the
code now works.

Yours
Ruiren

**Comment by tberkel** [comment] 2023-01-06 19:09
Good to hear and thanks for the update. I'll close this issue now.

**Closed by tberkel** 2023-01-06 19:09 UTC
