### ISSUE TITLE
Possible bug in RSGDF

### ISSUE THREAD

**Issue by awhite862** [pyscf/pyscf#1942] opened 2023-11-07 00:47 UTC
`RSGDF` fails (produces unreasonably high energies and doesn't converge) in a relatively simple case where `GDF` and `FFTDF` both provide reasonable results:

```
from pyscf.pbc import df, dft, gto
import numpy as np


def main():
    # unit cell
    a = np.array([[5.87704825, 0., 0.],
                  [-2.93852412, 5.08967308, 0.],
                  [0., 0., 9.4108361]])

    atom = '''
    Al   0.000000000000e+00   0.000000000000e+00   0.000000000000e+00;
    N    1.087472380182e-16   3.393115387675e+00   1.129307415351e+00;
    Al   1.087472380182e-16   3.393115387675e+00   4.705418050167e+00;
    N    0.000000000000e+00   0.000000000000e+00   5.834725465518e+00;
    '''
    cell = gto.M(a=a,
                 atom=atom,
                 unit='bohr',
                 basis='gth-szv',
                 pseudo={'Al': 'GTH-LDA', 'N': 'GTH-LDA'},
                 verbose=4,
                 precision=1.0e-12,
                 spin=0)
    cell.build()
    kpts = cell.make_kpts([1, 1, 1])

    # Regular GDF works fine for me (E = -23.5674653795703)
    #gdf = df.GDF(cell, kpts=kpts)

    # RSGDF doesn't work (unphysically high energies)
    gdf = df.RSGDF(cell, kpts=kpts)

    mf = dft.KRKS(cell, kpts=kpts, exxdiv=None, xc='PBE')
    mf.with_df = gdf
    mf.kernel()


if __name__ == '__main__':
    main()
```

**Comment by tberkel** [comment] 2023-11-07 22:44
Hm, for whatever it's worth, I can't reproduce this on PySCF 2.3.0
```
Python 3.10.6 (main, Oct  7 2022, 15:17:36) [Clang 12.0.0 ]
numpy 1.23.3  scipy 1.9.1
Date: Tue Nov  7 17:25:46 2023
PySCF version 2.3.0
...
E(GDF) =  -23.567465379567196
E(RSDF) =  -23.56746541133605
```

**Comment by awhite862** [comment] 2023-11-07 23:15
I can confirm that there is no issue with PySCF 2.3.0 (from PyPI), but the problem exists in PySCF 2.4.0 (from PyPI) and it is not fixed in the current `master` branch (installed from source)

**Comment by tberkel** [comment] 2023-11-07 23:16
Okay great, that's useful. Thanks @awhite862.

**Comment by verena-neufeld** [comment] 2023-11-09 00:23
It seems like this was introduced by commit 923d84c056c7abd41b1f9e9e0b5d6815016dbcf2

**Comment by verena-neufeld** [comment] 2023-11-12 23:20
Thanks for finding this bug @awhite862. It seems that it has been fixed now.

**Closed** 2023-11-14 20:35 UTC
