### ISSUE TITLE
Problem in CASCI Dipole Transition moment calculations

### ISSUE THREAD

**Issue by eronca** [pyscf/pyscf#390] opened 2019-07-23 19:46 UTC
Dear all, 

today I was trying to calculate excited state energies and transition dipole moments for a very small molecule (He-Be) using Pyscf.
The energies (compared to ORCA) are fine but transition dipole moments are very different and it seems also that they change with the run. 

To calculate them I started from the 030-transition_dipole.py example in 1-advanced.
The only things I changes in the script are the molecule, the basis and I added a loop to span different bond distances. With small changes in bond distance I can also get 2 order of magnitude difference in the transition dipole moment that is clearly unphysical. 

Could anyone help me to fix this problem?

You can find my run script below:

#!/usr/bin/env python
import sys
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
import h5py

from functools import reduce
import numpy
from pyscf import gto, scf, ao2mo, fci, mcscf
from pyscf import tools
from pyscf import symm

dist_range = numpy.arange(1.2,2.6,0.1)

energy_data = numpy.zeros((len(dist_range),3))
me_data = numpy.zeros((len(dist_range),5))
for n, dist in enumerate(dist_range):

    mol = gto.M(
        atom = [
                ['He', 0.0,  0.0,  0.0],
                ['Be', 0.0,  0.0,  dist]
               ],
        basis = 'def2-svpd',
        verbose = 0,
        symmetry = 1,
    #    symmetry_subgroup = 'D2h',
    )
    mf = scf.RHF(mol)
    mf.kernel()

    mc_mo = mf.mo_coeff
    #
    # 3. Exited states.  In this example, B2u are bright states.
    #
    # Here, mc.ci[0] is the first excited state.
    #
    mc = mcscf.CASCI(mf, 20, 6)
    mc.fcisolver = fci.direct_spin0.FCI(mol)
    mc.fcisolver.nroots = 7
    mc.kernel(mc_mo)
    

    energy_data[n,0] = dist
    energy_data[n,1:] = mc.e_tot[:2]
    print
    print "Energies:", mc.e_tot[:2]
    print
    sys.stdout.flush()
    
    #
    # 4. transition density matrix and transition dipole
    #
    # Be careful with the gauge origin of the dipole integrals
    #
    charges = mol.atom_charges()
    coords = mol.atom_coords()
    nuc_charge_center = numpy.einsum('z,zx->x', charges, coords) / charges.sum()
    mol.set_common_orig_(nuc_charge_center)
    dip_ints = mol.intor('cint1e_r_sph', comp=3)
    
    def makedip(ci_id1, ci_id2):
        # transform density matrix in MO representation
        t_dm1 = mc.fcisolver.trans_rdm1(mc.ci[ci_id1], mc.ci[ci_id2], mc.ncas, mc.nelecas)
        # transform density matrix to AO representation
        orbcas = mc_mo[:,mc.ncore:mc.ncore+mc.ncas]
        t_dm1_ao = reduce(numpy.dot, (orbcas, t_dm1, orbcas.T))
        # transition dipoles
        return numpy.einsum('xij,ji->x', dip_ints, t_dm1_ao)
    
    dip_array = numpy.zeros(4)
    count = 0
    for i in range(2):
      for j in range(2):
        dip = makedip(i,j)[0]
        print('Transition dipole between |%d> and |%d>'%(i,j), dip)
        dip_array[count] = dip
        count += 1
    sys.stdout.flush()
  
    me_data[n,0] = dist
    me_data[n,1:] = dip_array

numpy.savetxt('energy_data.txt', energy_data)
numpy.savetxt('me_data.txt', me_data)

Thank you in advance for the answer.

Bests

Enrico

**Comment by gkc1000** [comment] 2019-07-28 08:55
Hi Enrico,

I took a quick look. I think the problem is that the excited states are degenerate (e.g Pi symmetry). Since no symmetry is being used, then any linear combination of them is an eigenstate and so the transition dipole will vary widely depending on which linear combination happens to be converged.

You can do this in C2v symmetry instead and find the excited states in x or y symmetry to break the degeneracy.

Garnet

**Comment by gkc1000** [comment] 2019-07-28 08:58
BTW, in future, please ensure that the pasted text can be easily copied, and also attach some output.

**Comment by eronca** [comment] 2019-07-29 08:34
Thank you very much Garnet, 

I will try as soon as possible using symmetry. 

P.S: sorry about the input file I realized it was partially in code format only after I submitted the issue.

**Comment by gkc1000** [comment] 2019-10-12 01:49
Enrico - any news? Otherwise we will close this.

**Comment by eronca** [comment] 2019-10-12 05:18
Hi Garnet,

Using symmetry I fixed the problem.
Thanks for the suggestion.

You can close the issue

Bests

Enrico

**Closed** 2019-10-13 09:03 UTC
