### ISSUE TITLE
Installation via pip failing

### ISSUE THREAD

**Issue by quosta** [pyscf/pyscf#1206] opened 2022-03-10 20:13 UTC
The version uploaded to the PyPI repo seems to be missing a CMakelists.txt:
```
Failed to build pyscf
Installing collected packages: pyscf
    Running setup.py install for pyscf ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-m4au67r2/pyscf_660d58bc048641c6a59afff7a8102f1f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-m4au67r2/pyscf_660d58bc048641c6a59afff7a8102f1f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-2dqydpw5/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.10/pyscf
         cwd: /tmp/pip-install-m4au67r2/pyscf_660d58bc048641c6a59afff7a8102f1f/
    Complete output (10 lines):
    running install
    /usr/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    running build_ext
    Configuring extensions
    cmake -S/tmp/pip-install-m4au67r2/pyscf_660d58bc048641c6a59afff7a8102f1f/pyscf/lib -Bbuild/temp.linux-x86_64-3.10
    CMake Error: The source directory "/tmp/pip-install-m4au67r2/pyscf_660d58bc048641c6a59afff7a8102f1f/pyscf/lib" does not appear to contain CMakeLists.txt.
    Specify --help for usage, or press the help button on the CMake GUI.
    error: command '/usr/bin/cmake' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-m4au67r2/pyscf_660d58bc048641c6a59afff7a8102f1f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-m4au67r2/pyscf_660d58bc048641c6a59afff7a8102f1f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-2dqydpw5/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.10/pyscf Check the logs for full command output.
``` 

Everything works fine with the version 2.0.1 downloaded from GitHub and installed locally

**Comment by jamesETsmith** [comment] 2022-03-11 17:08
@quosta, thanks for letting us know you're having problems. I think this is a duplicate of #1112 so I'm going to close it, but if you disagree feel free to reopen.

**Closed by jamesETsmith** 2022-03-11 17:08 UTC
