### ISSUE TITLE
Please update h5py3 config in lib/misc.py of version 1.7 on Pypi

### ISSUE THREAD

**Issue by SHw-1313** [pyscf/pyscf#1807] opened 2023-07-25 13:12 UTC
I am using semiempirical method of pyscf v1.7 in our MD framework. For the convenience of users, could you please update the h5py3 config of version 1.7 on Pypi, so that the users can download and use it immediately? Besides, when would the other semiempirical methods, like AM1/PM6, be supported by latest version of pyscf?

**Comment by verena-neufeld** [comment] 2023-07-28 04:33
I don't use pyscf for semi empirical methods myself, so maybe @sunqm should correct me if I'm wrong:
Does the pyscf extension in https://github.com/pyscf/semiempirical help you? PySCF has moved some modules out to extension at some point, maybe this is the code you are looking for? If yes (and again I don't know), you can use the latest PySCF.

**Comment by sunqm** [comment] 2024-08-13 01:18
The pyscf-2.* version is compatible with a wide range of h5py versions. I'll close this issue as the issue is outdated.

**Closed by sunqm** 2024-08-13 01:18 UTC
