### ISSUE TITLE
DFT converges to strange energy for large molecule

### ISSUE THREAD

**Issue by ssnam92** [pyscf/pyscf#804] opened 2021-01-23 09:17 UTC
Dear all

I tried to calculate a large molecule (46 atoms) with DFT, and I find out that DFT converges to very strange energy
Here's my input:

```
mol=gto.M(atom='''
C  -11.104710  -0.945169  -5.389029
C  -10.337902  -0.757446  -4.307630
C   -8.885014  -0.758844  -4.326279
C   -8.116936  -0.569444  -3.235814
C   -6.670289  -0.569923  -3.248524
C   -5.903472  -0.380241  -2.155245
C   -4.456938  -0.381135  -2.166472
C   -3.690869  -0.191520  -1.074454
C   -2.238978  -0.191969  -1.088715
C   -1.479694  -0.000000  -0.000000
C    0.000000   0.000000   0.000000
C    0.759530   1.105453  -0.000000
C    2.211202   1.091066   0.001292
C    2.977746   2.199482  -0.002347
C    4.423592   2.188139  -0.002792
C    5.190753   3.298586  -0.007339
C    6.635448   3.286583  -0.007722
C    7.403847   4.396078  -0.012414
C    8.849842   4.381757  -0.012944
C    9.619466   5.487827  -0.018034
C   11.072132   5.467399  -0.018704
C   11.840410   6.564035  -0.023893
H  -12.191433  -0.935476  -5.324965
H  -10.813754  -0.590498  -3.337530
H  -10.665475  -1.114534  -6.372947
H   -8.603408  -0.403203  -2.270262
H   -8.403723  -0.925503  -5.294325
H   -6.390907  -0.213958  -1.190277
H   -6.183653  -0.736257  -4.213807
H   -4.174998  -0.024470  -0.108013
H   -3.969520  -0.547482  -3.131407
H   -1.978700   0.164503   0.960850
H   -1.753519  -0.356655  -2.054658
H    0.274160   2.085369  -0.005264
H    0.498833  -0.974898   0.004542
H    2.490266   3.178614  -0.005855
H    2.695154   0.110226   0.004366
H    4.703094   4.277604  -0.010947
H    4.911247   1.209102   0.000778
H    6.918104   5.375998  -0.016205
H    7.122642   2.307278  -0.003975
H    9.139342   6.470666  -0.022016
H    9.335305   3.401513  -0.009019
H   11.402457   7.562974  -0.028010
H   11.546788   4.482472  -0.014679
H   12.927044   6.497845  -0.024200
''',basis='aug-cc-pVTZ',verbose=4)
myDFT=dft.RKS(mol).density_fit()
myDFT.xc='pbe'
myDFT=scf.addons.remove_linear_dep(myDFT,threshold=1e-6,lindep=1e-8)
myDFT.kernel()
```

Proper energy should be near -851.8 Hartree, but the energy drops dramatically on the 1st cycle:

```init E= -853.744800840401

WARN: Singularity detected in overlap matrix (condition number = 1.01e+08). SCF may be inaccurate and hard to converge.

  HOMO = 0.0241967649359005  LUMO = 0.07800510966329
cycle= 1 E= -1018.40700736467  delta_E= -165  |g|=   20  |ddm|= 8.88e+04
  HOMO = 0.0665014766818567  LUMO = 0.0795007801217087
```
I tried threshold up to 1e-1, but I don't think this number makes sense.

For larger molecules (50 and 54 atoms) the problem does not occur.

How can I solve this problem? Is this a problem of linear dependency? Any help will be very appreciated.

**Comment by gkc1000** [comment] 2021-01-23 09:23
Check your bond distances and make sure you don't have two atoms very close
to each other, which will cause linear dependency.

**Comment by ssnam92** [comment] 2021-01-23 09:32
Thank you for your prompt reply. I checked geometry and it does not have any problem.
If this is a linear dependency problem, how can I solve it? 
Are there any options that I can try other than `scf.addons.remove_linear_dep` ?

**Comment by fishjojo** [comment] 2021-01-27 01:54
Your system is a diradical. RKS won't work. You may try fractional occupations or UKS or ROKS.

**Comment by ssnam92** [comment] 2021-01-27 02:31
@fishjojo How can I check if the system is a diradical or not?
I tried UKS and energy also oscillates below -1000Harteree, 
```
SCF not converged.
SCF energy = -1028.72566679828 after 50 cycles  <S^2> = -8.7396756e-12  2S+1 = 1
```
(LDA result)
and the use of smaller basis sets does not cause this problem  (AVDZ or def2-TZVPD).

**Comment by fishjojo** [comment] 2021-01-27 02:37
I was wrong. I thought it was a double bond being rotated by 90 degree. I'll take a look.

**Comment by sunqm** [comment] 2021-01-28 21:39
The convergence and big drop of energy is likely caused by the small gap in the
system. You can give the second order algorithm a trial

```
scf.fast_newton(myDFT)
```

On Sat, Jan 23, 2021 at 01:17:57AM -0800, ssnam92 wrote:
> Dear all
> 
> I tried to calculate a large molecule (46 atoms) with DFT, and I find out that DFT converges to very strange energy
> Here's my input:
> 
> ```
> mol=gto.M(atom='''
> C  -11.104710  -0.945169  -5.389029
> C  -10.337902  -0.757446  -4.307630
> C   -8.885014  -0.758844  -4.326279
> C   -8.116936  -0.569444  -3.235814
> C   -6.670289  -0.569923  -3.248524
> C   -5.903472  -0.380241  -2.155245
> C   -4.456938  -0.381135  -2.166472
> C   -3.690869  -0.191520  -1.074454
> C   -2.238978  -0.191969  -1.088715
> C   -1.479694  -0.000000  -0.000000
> C    0.000000   0.000000   0.000000
> C    0.759530   1.105453  -0.000000
> C    2.211202   1.091066   0.001292
> C    2.977746   2.199482  -0.002347
> C    4.423592   2.188139  -0.002792
> C    5.190753   3.298586  -0.007339
> C    6.635448   3.286583  -0.007722
> C    7.403847   4.396078  -0.012414
> C    8.849842   4.381757  -0.012944
> C    9.619466   5.487827  -0.018034
> C   11.072132   5.467399  -0.018704
> C   11.840410   6.564035  -0.023893
> H  -12.191433  -0.935476  -5.324965
> H  -10.813754  -0.590498  -3.337530
> H  -10.665475  -1.114534  -6.372947
> H   -8.603408  -0.403203  -2.270262
> H   -8.403723  -0.925503  -5.294325
> H   -6.390907  -0.213958  -1.190277
> H   -6.183653  -0.736257  -4.213807
> H   -4.174998  -0.024470  -0.108013
> H   -3.969520  -0.547482  -3.131407
> H   -1.978700   0.164503   0.960850
> H   -1.753519  -0.356655  -2.054658
> H    0.274160   2.085369  -0.005264
> H    0.498833  -0.974898   0.004542
> H    2.490266   3.178614  -0.005855
> H    2.695154   0.110226   0.004366
> H    4.703094   4.277604  -0.010947
> H    4.911247   1.209102   0.000778
> H    6.918104   5.375998  -0.016205
> H    7.122642   2.307278  -0.003975
> H    9.139342   6.470666  -0.022016
> H    9.335305   3.401513  -0.009019
> H   11.402457   7.562974  -0.028010
> H   11.546788   4.482472  -0.014679
> H   12.927044   6.497845  -0.024200
> ''',basis='aug-cc-pVTZ',verbose=4)
> myDFT=dft.RKS(mol).density_fit()
> myDFT.xc='pbe'
> myDFT.scf.addons.remove_linear_dep(myDFT,threshold=1e-6,lindep=1e-8)
> myDFT.kernel()
> ```
> 
> Proper energy should be near -851.8 Hartree, but the energy drops dramatically on the 1st cycle:
> 
> ```init E= -853.744800840401
> 
> WARN: Singularity detected in overlap matrix (condition number = 1.01e+08). SCF may be inaccurate and hard to converge.
> 
>   HOMO = 0.0241967649359005  LUMO = 0.07800510966329
> cycle= 1 E= -1018.40700736467  delta_E= -165  |g|=   20  |ddm|= 8.88e+04
>   HOMO = 0.0665014766818567  LUMO = 0.0795007801217087
> ```
> I tried threshold up to 1e-1, but I don't think this number makes sense.
> 
> For larger molecules (50 and 54 atoms) the problem does not occur.
> 
> How can I solve this problem? Is this a problem of linear dependency? Any help will be very appreciated.
> 
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/pyscf/pyscf/issues/804

--

**Comment by ssnam92** [comment] 2021-01-29 05:43
Dear @sunqm 
SOSCF gives a much more stable SCF procedure, but now the energy is too high
```
  HOMO = -0.30702024592604  LUMO = -0.295542872071245
Initial guess E= -831.33930642  |g|= 3.43348
macro= 0  E= -832.241942378911  delta_E= -0.902636  |g|= 1.54095  3 KF 15 JK
macro= 1  E= -832.844066266833  delta_E= -0.602124  |g|= 1.47187  2 KF 14 JK
macro= 2  E= -833.797997237514  delta_E= -0.953931  |g|= 1.23096  2 KF 14 JK
macro= 3  E= -834.440132812852  delta_E= -0.642136  |g|= 0.676908  3 KF 15 JK
macro= 4  E= -835.52327883689  delta_E= -1.08315  |g|= 0.265227  3 KF 17 JK
macro= 5  E= -835.980611553992  delta_E= -0.457333  |g|= 0.193105  3 KF 18 JK
macro= 6  E= -836.243160396848  delta_E= -0.262549  |g|= 0.140886  2 KF 8 JK
macro= 7  E= -836.328587262444  delta_E= -0.0854269  |g|= 0.044793  3 KF 13 JK
macro= 8  E= -836.344141693504  delta_E= -0.0155544  |g|= 0.00725942  3 KF 12 JK
macro= 9  E= -836.346164155645  delta_E= -0.00202246  |g|= 0.0016935  3 KF 9 JK
macro= 10  E= -836.346378797016  delta_E= -0.000214641  |g|= 0.000675744  2 KF 6 JK
macro= 11  E= -836.346535212871  delta_E= -0.000156416  |g|= 0.000375326  2 KF 7 JK
macro= 12  E= -836.346626872866  delta_E= -9.166e-05  |g|= 6.2475e-05  2 KF 9 JK
macro= 13  E= -836.346637600819  delta_E= -1.0728e-05  |g|= 2.23563e-05  1 KF 4 JK
macro= 14  E= -836.3466383161  delta_E= -7.15281e-07  |g|= 8.98761e-06  1 KF 2 JK
macro= 15  E= -836.346638358003  delta_E= -4.19027e-08  |g|= 8.83558e-06  1 KF 2 JK
macro= 16  E= -836.346638360147  delta_E= -2.14413e-09  |g|= 8.85007e-06  1 KF 2 JK
macro= 17  E= -836.34663836004  delta_E= 1.06866e-10  |g|= 8.85082e-06  1 KF 2 JK
Canonicalize SCF orbitals
macro X = 18  E=-836.34663836004  |g|= 8.85082e-06  total 39 KF 188 JK

WARN: HOMO -0.29058429324323853 > LUMO -0.29636046149529205 was found in the canonicalized

converged SCF energy = -836.34663836004
```

I tried an initial guess from a smaller basis calculation: (do I using it properly?)
```
mol1=gto.M(atom=coord,basis='aug-cc-pVDZ')
mf1=dft.RKS(mol1).density_fit()
mf1.xc='pbe'
mf1.verbose=4
mf1.kernel()
mo1=mf1.mo_coeff

mol2=gto.M(atom=coord,basis='aug-cc-pVTZ')
mf2=dft.RKS(mol2).density_fit().newton()
mf2.xc='pbe'
mf2.verbose=4
mf2.mo_coeff=scf.addons.project_mo_nr2nr(mol1, mo1, mol2)
occ=np.zeros(mol1.nao_nr())
occ[:mol1.nelectron//2]=2
mf2.mo_occ=occ
mf2.kernel()
```

AVDZ gives -851.588287337325 but AVTZ with SOSCF gives -844.448709340874

**Comment by susilehtola** [comment] 2021-02-28 19:55
This reminds me: it would be cool to have the projection-free initial guess in PySCF (see [doi:10.1016/j.cplett.2012.02.012](https://doi.org/10.1016/j.cplett.2012.02.012)). One can evaluate the Fock matrix in the new basis `F_UV = T_UV + V_UV + J_UV + K_UV` directly from the density matrix in the old basis, if one can just construct the mixed-basis integrals: `J_UV = \sum_uv (UV|uv) P_uv` and `K_UV = \sum_uv (uU|vV) P_uv`.

For a pure DFT method this is a bit simpler, since the Coulomb matrix only needs the simple mixed-basis integrals; the DFT code just has to evaluate the density variables with the old basis, and calculate the Fock matrix contributions in the new basis...

**Comment by susilehtola** [comment] 2021-02-28 20:05
@ssnam92 the problem with the Newton method is that it converges onto the closest extremum, which looks like a saddle point; you should be able to get out of it by running stability analysis and restarting the SCF from that.

However, the system is pretty simple: it's a neutral molecule, and it is trivial to converge in a small basis. First, since this is DFT, the polarization consistent sets (pc-n) are much more computationally efficient, since aug-cc-pVTZ is meant for post-Hartree-Fock calculations. I ran an initial guess in the single-zeta pc-0 basis, it converged to the energy -849.427633149443 in 12 iterations. Next, I ran a calculation in the augmented triple-zeta aug-pc-2 basis, started from the pc-0 wave function; this also converges in 12 iterations and results in the energy -851.843963692761, which is indeed near  -851.8 Hartree.

Here's the input I used
```
from pyscf import gto, scf, dft

mol=gto.M(atom='''
C  -11.104710  -0.945169  -5.389029
C  -10.337902  -0.757446  -4.307630
C   -8.885014  -0.758844  -4.326279
C   -8.116936  -0.569444  -3.235814
C   -6.670289  -0.569923  -3.248524
C   -5.903472  -0.380241  -2.155245
C   -4.456938  -0.381135  -2.166472
C   -3.690869  -0.191520  -1.074454
C   -2.238978  -0.191969  -1.088715
C   -1.479694  -0.000000  -0.000000
C    0.000000   0.000000   0.000000
C    0.759530   1.105453  -0.000000
C    2.211202   1.091066   0.001292
C    2.977746   2.199482  -0.002347
C    4.423592   2.188139  -0.002792
C    5.190753   3.298586  -0.007339
C    6.635448   3.286583  -0.007722
C    7.403847   4.396078  -0.012414
C    8.849842   4.381757  -0.012944
C    9.619466   5.487827  -0.018034
C   11.072132   5.467399  -0.018704
C   11.840410   6.564035  -0.023893
H  -12.191433  -0.935476  -5.324965
H  -10.813754  -0.590498  -3.337530
H  -10.665475  -1.114534  -6.372947
H   -8.603408  -0.403203  -2.270262
H   -8.403723  -0.925503  -5.294325
H   -6.390907  -0.213958  -1.190277
H   -6.183653  -0.736257  -4.213807
H   -4.174998  -0.024470  -0.108013
H   -3.969520  -0.547482  -3.131407
H   -1.978700   0.164503   0.960850
H   -1.753519  -0.356655  -2.054658
H    0.274160   2.085369  -0.005264
H    0.498833  -0.974898   0.004542
H    2.490266   3.178614  -0.005855
H    2.695154   0.110226   0.004366
H    4.703094   4.277604  -0.010947
H    4.911247   1.209102   0.000778
H    6.918104   5.375998  -0.016205
H    7.122642   2.307278  -0.003975
H    9.139342   6.470666  -0.022016
H    9.335305   3.401513  -0.009019
H   11.402457   7.562974  -0.028010
H   11.546788   4.482472  -0.014679
H   12.927044   6.497845  -0.024200
''',basis='pc-0',verbose=4)

myDFT=dft.RKS(mol).density_fit()
myDFT.with_df.auxbasis='def2-universal-jfit'
myDFT.xc='pbe'
myDFT.chkfile='myDFT.h5'
myDFT=scf.addons.remove_linear_dep(myDFT,threshold=1e-5,lindep=1e-8)
myDFT.kernel()

mol=gto.M(atom='''
C  -11.104710  -0.945169  -5.389029
C  -10.337902  -0.757446  -4.307630
C   -8.885014  -0.758844  -4.326279
C   -8.116936  -0.569444  -3.235814
C   -6.670289  -0.569923  -3.248524
C   -5.903472  -0.380241  -2.155245
C   -4.456938  -0.381135  -2.166472
C   -3.690869  -0.191520  -1.074454
C   -2.238978  -0.191969  -1.088715
C   -1.479694  -0.000000  -0.000000
C    0.000000   0.000000   0.000000
C    0.759530   1.105453  -0.000000
C    2.211202   1.091066   0.001292
C    2.977746   2.199482  -0.002347
C    4.423592   2.188139  -0.002792
C    5.190753   3.298586  -0.007339
C    6.635448   3.286583  -0.007722
C    7.403847   4.396078  -0.012414
C    8.849842   4.381757  -0.012944
C    9.619466   5.487827  -0.018034
C   11.072132   5.467399  -0.018704
C   11.840410   6.564035  -0.023893
H  -12.191433  -0.935476  -5.324965
H  -10.813754  -0.590498  -3.337530
H  -10.665475  -1.114534  -6.372947
H   -8.603408  -0.403203  -2.270262
H   -8.403723  -0.925503  -5.294325
H   -6.390907  -0.213958  -1.190277
H   -6.183653  -0.736257  -4.213807
H   -4.174998  -0.024470  -0.108013
H   -3.969520  -0.547482  -3.131407
H   -1.978700   0.164503   0.960850
H   -1.753519  -0.356655  -2.054658
H    0.274160   2.085369  -0.005264
H    0.498833  -0.974898   0.004542
H    2.490266   3.178614  -0.005855
H    2.695154   0.110226   0.004366
H    4.703094   4.277604  -0.010947
H    4.911247   1.209102   0.000778
H    6.918104   5.375998  -0.016205
H    7.122642   2.307278  -0.003975
H    9.139342   6.470666  -0.022016
H    9.335305   3.401513  -0.009019
H   11.402457   7.562974  -0.028010
H   11.546788   4.482472  -0.014679
H   12.927044   6.497845  -0.024200
''',basis='aug-pc-2',verbose=4)

myDFT=dft.RKS(mol).density_fit()
myDFT.with_df.auxbasis='def2-universal-jfit'
myDFT.xc='pbe'
myDFT.chkfile='myDFT.h5'
myDFT.init_guess='chkfile'
myDFT=scf.addons.remove_linear_dep(myDFT,threshold=1e-5,lindep=1e-8)
myDFT.kernel()
```

**Comment by sunqm** [comment] 2023-03-22 08:41
The regular SCF iteration with AVTZ basis seems converging smoothly after applying PR #1008 . Also Susi's script is able to converge to this system. I'll close this issue for now.

**Closed by sunqm** 2023-03-22 08:41 UTC
