### ISSUE TITLE
UHF with customized Hamiltonian

### ISSUE THREAD

**Issue by DYehorova** [pyscf/pyscf#923] opened 2021-04-27 01:22 UTC
Good afternoon,

I have an issue running UHF with customized hamiltonian. The calculation works well if the calculation is done with RHF (mf = scf.RHF(mol)). I have used an example of the customary RHF provided in the manual and replaced mf = scf.RHF(mol) with mf = scf.UHF(mol).  scf.UHF(mol) works for non-customized hamiltonian. The 1 and 2 e integrals that are used are made for 1d Hubbard model. Thank you in advance for any help you are able to provide. 

def initialize_UHF( self, h_site, V_site ):
        Norbs = self.Nele
        mol = gto.M()
        mol.nelectron = self.Nele
        mol.imncore_anyway = True
        mf = scf.UHF(mol)
        mf.get_hcore = lambda *args: h_site
        mf.get_ovlp = lambda *args: np.eye(Norbs)
        mf._eri = ao2mo.restore(8, V_site, Norbs)
        mf.kernel()
        mfRDM = mf.make_rdm1()
        return mfRDM

and the error that I receive is :

 mf1RDM = self.initialize_UHF(h_site, V_site)
  File "/storage/home/hcoda1/2/dyehorova3/research/pDMET.py", line 317, in initialize_UHF
    mf.kernel()
  File "/storage/home/hcoda1/2/dyehorova3/.conda/envs/dyehorova3/lib/python3.8/site-packages/pyscf/lib/misc.py", line 598, in aliased_fn
    return getattr(self, fname)(*args, **kwargs)
  File "/storage/home/hcoda1/2/dyehorova3/.conda/envs/dyehorova3/lib/python3.8/site-packages/pyscf/scf/hf.py", line 1642, in scf
    kernel(self, self.conv_tol, self.conv_tol_grad,
  File "/storage/home/hcoda1/2/dyehorova3/.conda/envs/dyehorova3/lib/python3.8/site-packages/pyscf/scf/hf.py", line 122, in kernel
    dm = mf.get_init_guess(mol, mf.init_guess)
  File "/storage/home/hcoda1/2/dyehorova3/.conda/envs/dyehorova3/lib/python3.8/site-packages/pyscf/scf/hf.py", line 1572, in get_init_guess
    dm = self.init_guess_by_1e(mol)
  File "/storage/home/hcoda1/2/dyehorova3/.conda/envs/dyehorova3/lib/python3.8/site-packages/pyscf/scf/uhf.py", line 848, in init_guess_by_1e
    for b0, b1, p0, p1 in mol.aoslice_by_atom():
  File "/storage/home/hcoda1/2/dyehorova3/.conda/envs/dyehorova3/lib/python3.8/site-packages/pyscf/gto/mole.py", line 1647, in aoslice_by_atom
    shell_start[0] = 0
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by verena-neufeld** [comment] 2021-04-27 02:19
I had a brief look. Could it be that this line: https://github.com/pyscf/pyscf/blob/master/pyscf/gto/mole.py#L1656 gets called with `mol.natm` being equal to zero? Just to check: Are you referring to this example which you said you modified: https://github.com/pyscf/pyscf/blob/master/examples/scf/40-customizing_hamiltonian.py ? Interestingly, the example says that an initial guess for the SCF calculation should be specified but then it does not seem to specify an initial guess. I am not sure but on first glance it seems RHF does not call `mol.natm` when estimating the initial guess for the SCF calc. Would your problem run fine if you specified an initial guess for your SCF calculation?

**Comment by sunqm** [comment] 2021-04-27 08:36
A quick fix can be
```
mf.init_guess = 'hcore'
```

**Comment by verena-neufeld** [comment] 2021-04-27 14:41
@sunqm would this also be an issue for other SCF classes (other than RHF and UHF)?

**Comment by sunqm** [comment] 2021-04-27 18:35
In RHF class, this corner case has been considered. Initial guess can be switched to "hcore" automatically. Error here is caused by a different place in UHF initial guess function which tries to break the spin-symmetry between the spin-up and spin-down densities using information from atoms.

**Comment by DYehorova** [comment] 2021-05-10 14:56
Unfortunately adding 
mf.init_guess = 'hcore'
 or 
mf.init_guess = '1e' 
as suggested in this code (https://github.com/pyscf/pyscf.github.io/blob/master/examples/scf/15-initial_guess.py ) didn't work for me, I continued to receive the same error as before. 
Instead, I diagonalized my 1 electron integral and used that as an initial guess for the density matrix and that worked.

**Comment by sunqm** [comment] 2023-03-22 08:22
Fixed in PR #1359

**Closed by sunqm** 2023-03-22 08:22 UTC
