### ISSUE TITLE
Building CISD wavefunction

### ISSUE THREAD

**Issue by AlexisRalli** [pyscf/pyscf#1736] opened 2023-05-17 19:29 UTC
I'm trying to build the CISD wavefunction via the following implementation:

```
from pyscf import gto, scf, ci, fci
from pyscf.ci.cisd import to_fcivec
import numpy as np


mol    = gto.M(
    
# atom  = [
#           ['H', ( 0., 0., 0.)],
#           ['H', ( 0.,  0.74, 0.)]],
    
atom  = [['O', ( 0., 0.    , 0.   )],
          ['H', ( 0., -0.957, 0.987)],
          ['H', ( 0.,  0.957, 0.987)]],
    
 basis = 'sto-3g')

norb   = mol.nao_nr()
neleca = mol.nelectron//2
nelecb = neleca

mf        = scf.RHF(mol).run()
myci      = ci.CISD(mf)
ecisd,ci0 = myci.kernel()

cisdWFN   = to_fcivec(ci0,norb,(neleca,nelecb))

print()
zero_ket = np.zeros(2*norb).astype(int)
occslst = fci.cistring._gen_occslst(range(norb), mol.nelectron//2)
state_vec = np.zeros(2**(2*norb)) 
for i,occsa in enumerate(occslst):
    for j,occsb in enumerate(occslst):
        
        # check amplitude is above certain threshold
        if abs(cisdWFN[i,j])>1e-10:
            
            # encoding: |↓↑ ↓↑ ↓↑ ↓↑ ... > 
            even = 2* occsa
            odd = 2* occsb + 1
            det = zero_ket.copy()
            det[even] = 1
            det[odd] = 1

            binary = ''.join(det.astype(str).tolist())
            print(f'{cisdWFN[i,j]} |{binary}>')

            state_ind = int(binary,2)
            state_vec[state_ind] = cisdWFN[i,j]

assert np.isclose(np.linalg.norm(state_vec), 1), 'quantum state is NOT normalized'

##  <psi|H|psi> != E_ccid where |psi> = state_vec
```

However, the output wavefunction does not seem to give the correct energy when measuring the expectation value with H. Is there something I am doing wrong? I've been looking at:

1. https://github.com/pyscf/pyscf/issues/327
2. https://github.com/pyscf/pyscf/blob/master/examples/fci/11-large_ci.py
3. https://github.com/pyscf/pyscf/issues/1627

I've also tried the following:
```
from pyscf.ci.cisd import cisdvec_to_amplitudes
from pyscf.cc.addons import spatial2spin

def array_to_dict_nonzero_indices(arr, tol=1e-10):
    """
    """
    where_nonzero = np.where(~np.isclose(arr, 0, atol=tol))
    nonzero_indices = list(zip(*where_nonzero))
    return dict(zip(nonzero_indices, arr[where_nonzero]))

c0,t1,t2  = cisdvec_to_amplitudes(ci0,myci.nmo,myci.nocc)

t1 = spatial2spin(t1, orbspin=None)
t2 = spatial2spin(t2, orbspin=None)


no, nv = t1.shape
nmo = no + nv

# dictionary of single aplitudes of form {(i,j):t_ij}
single_amplitudes = np.zeros((nmo, nmo))
single_amplitudes[no:,:no] = t1.T
single_amp_dict = array_to_dict_nonzero_indices(single_amplitudes)

# dictionary of double aplitudes of form {(i,j,k,l):t_ijkl}
double_amplitudes = np.zeros((nmo, nmo, nmo, nmo))
double_amplitudes[no:,:no,no:,:no] = .25 * t2.transpose(2,0,3,1)
double_amp_dict = array_to_dict_nonzero_indices(double_amplitudes)

# ^ == creation ... and no hat == annihilation  
raising_lowering_SINGLES = []
for (i, j), t_ij in single_amp_dict.items():
    raising_lowering_SINGLES.append((f'{i}^ {j}', t_ij))
    
raising_lowering_DOUBLES = []
for (i, j, k, l), t_ijkl in double_amp_dict.items():
    raising_lowering_DOUBLES.append((f'{i}^ {j} {k}^ {l}', t_ijkl))

    
print('HF coeff:', c0)
print()
print(raising_lowering_SINGLES)
print()
print(raising_lowering_DOUBLES)
```

Any help would be appreciated! Thanks :)

**Comment by sunqm** [comment] 2023-07-22 22:35
In FCI determinant basis, spin-orbitals are sorted as |up,up,up,..., down,down,down...> .
```
            even = 2* occsa
            odd = 2* occsb + 1
```
I'm not clear what the `even` and `odd` in your code represent for. It looks like your assumption of FCI determinant is the |up,down,up,down,...> convention.

**Comment by sunqm** [comment] 2024-08-16 07:05
This question appears to be a duplicate of #1627, so I’ll close it. Feel free to reopen if needed.

**Closed by sunqm** 2024-08-16 07:05 UTC
