### ISSUE TITLE
Test workflow for AArch64

### ISSUE THREAD

**Issue by kkyusuke** [pyscf/pyscf#1277] opened 2022-06-07 08:16 UTC
The release workflow supports AArch64, but the test doesn't.
It's not ideal to publish without tests, so I'd like to add CI configuration.

GitHub Actions doesn't have native AArch64 environment, so we need to use QEMU.
Note that it has 6-hour time limit for each execution.

I'd like to discuss with developers to find a best way. @mjw99

**Comment by mjw99** [comment] 2022-06-07 08:56
I've just tried the above with an updated actions/checkout@v3 and docker/setup-qemu-action@v2
I see an error in building at https://github.com/mjw99/pyscf/runs/6770537388?check_suite_focus=true
```
........
-- Looking for ffsll
-- Looking for ffsll - not found
CMake Error at CMakeLists.txt:72 (message):
  A required library with BLAS API not found.
```

**Comment by kkyusuke** [comment] 2022-06-07 14:44
The build in my CI was OK ([here](https://github.com/kkyusuke/pyscf/runs/6750960301?check_suite_focus=true)), but the branch was one week old, based on  https://github.com/pyscf/pyscf/commit/9d5b5bd309d1cc55fbd1a0ec76e26b5b0c7f76af.

**Comment by mjw99** [comment] 2022-06-08 16:02
Yes; that fixed it... but I am seeing the same timeout [timeout](https://github.com/mjw99/pyscf/runs/6791216625?check_suite_focus=true) as you (even with a few tweaks).

**Comment by sunqm** [comment] 2022-06-08 19:10
Excluding tests in pbc.df, pbc.cc and adc can be a temporary solution. We can optimize the tests in the future

**Comment by kkyusuke** [comment] 2022-06-10 13:58
Thank you @sunqm , it seems OK by excluding pbc.df, pbc.cc and adc. I'll make a pull request.

**Comment by hebrewsnabla** [comment] 2022-06-12 05:19
Since py3.6 is excluded in the recent PR, should it also be excluded in the release workflow?
And why py3.10 is included in the release workflow but not in this test workflow?

**Comment by kkyusuke** [comment] 2022-06-14 07:53
The fail in py3.6 is due to h5py. 
Recent pip automatically finds a good (older) version, so no error occurs. However, test CI's pip cannot.
If publish CI also fails, py3.6 should be removed. If OK, we need to check why only test CI fails.
Does someone know?

I forgot about py3.10. Someone (or I) should update the yaml file.

**Comment by kkyusuke** [comment] 2022-06-14 07:58
@sunqm, you mentioned about the test optimization (pbc.df, pbc.cc and adc).
Could you tell me more? If possible, I'd like to contribute on it.

**Comment by sunqm** [comment] 2022-08-12 17:08
> @sunqm, you mentioned about the test optimization (pbc.df, pbc.cc and adc). Could you tell me more? If possible, I'd like to contribute on it.

pbc.df will be replaced by new algorithms and tests in this module shall be more stable and fast in the future.

Some tests in pbc.cc and adc runs an entire test system to get the total energy for validation. For the purpose of testing individual functions, computing the energy is not needed (and sometimes not reliable). We just need to make sure (1) important functions and branches are covered in the tests and (2) the output are reproducible given fixed input. Some tests in the two modules can be replaced by true unittest for specific functions

**Comment by sunqm** [comment] 2023-03-29 02:26
Tests for aarch64 are deployed on github ci actions . Tests for pbc and some other modules are excluded because they are slow.

**Closed by sunqm** 2023-03-29 02:26 UTC
