### ISSUE TITLE
Examles and tutorials, SystemError: NULL result without error in PyObject_Call

### ISSUE THREAD

**Issue by drmcnelson** [pyscf/pyscf#396] opened 2019-07-31 00:27 UTC
The examples and tutorials, are not working.   I am working on Fedora 30 with Cinnamon desktop, and a fresh install of pyscf view pip.

Here is the traceback from  0-readme.py.   Similar tracebacks are produced by all of the examples and tutorials that I have tried.

```
  File "./0-readme.py", line 31, in <module>
    print('E=%.15g' % mf.kernel())
  File "/usr/lib64/python2.7/site-packages/pyscf/lib/misc.py", line 584, in aliased_fn
    return getattr(self, fname)(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/pyscf/scf/hf.py", line 1501, in scf
    conv_check=self.conv_check, **kwargs)
  File "/usr/lib64/python2.7/site-packages/pyscf/scf/hf.py", line 121, in kernel
    dm = mf.get_init_guess(mol, mf.init_guess)
  File "/usr/lib64/python2.7/site-packages/pyscf/scf/hf.py", line 1445, in get_init_guess
    dm = self.init_guess_by_minao(mol)
  File "/usr/lib64/python2.7/site-packages/pyscf/scf/hf.py", line 1396, in init_guess_by_minao
    return init_guess_by_minao(mol)
  File "/usr/lib64/python2.7/site-packages/pyscf/scf/hf.py", line 433, in init_guess_by_minao
    c = addons.project_mo_nr2nr(pmol, numpy.eye(pmol.nao_nr()), mol)
  File "/usr/lib64/python2.7/site-packages/pyscf/scf/addons.py", line 303, in project_mo_nr2nr
    return lib.cho_solve(s22, numpy.dot(s21, mo1))
  File "/usr/lib64/python2.7/site-packages/pyscf/lib/linalg_helper.py", line 1394, in cho_solve
    return scipy.linalg.solve(a, b, sym_pos=True)
  File "/usr/lib64/python2.7/site-packages/scipy/linalg/basic.py", line 249, in solve
    overwrite_b=overwrite_b)
SystemError: NULL result without error in PyObject_Call

```

ystemError: NULL result without error in PyObject_Call

**Comment by sunqm** [comment] 2019-08-03 08:50
It may be caused by the bug in numpy-1.16.  https://github.com/numpy/numpy/issues/13808 . What's your numpy version? If it's 1.16.* or 1.17, can you try to downgrade it to 1.15 and rerun the test?

**Comment by sunqm** [comment] 2019-10-21 04:13
the memory leak bug is fixed in latest numpy updates

**Closed by sunqm** 2019-10-21 04:13 UTC
